// PROPÓSITO: Crear post "Kit completo para empezar a pescar 2026" en DB local
// FECHA: 2026-08-11
// Uso: npx tsx scripts/create-kit-post.ts
import { createPost } from '../src/data/blog-queries'

const products = [
  {
    title: 'Abu Garcia Tormentor2 — Caña Spinning 2.40m 10-30g',
    rating: 4.3,
    image: 'https://m.media-amazon.com/images/I/51qg8MlZBxL._AC_SX679_.jpg',
    scores: { Construcción: 82, Acción: 84, Lance: 86, Sensibilidad: 80, 'Calidad/Precio': 92 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0DLGKNG9P', price: '34,99€' }],
    slug: 'abu-garcia-tormentor2---caa-spinning-240m-10-30g',
  },
  {
    title: 'Shimano FX 2500 — Carrete Spinning para empezar',
    rating: 4.4,
    image: 'https://m.media-amazon.com/images/I/61o6OqhGNRL._AC_SL1500_.jpg',
    scores: { Construcción: 78, Suavidad: 76, Frenado: 80, Resistencia: 74, 'Calidad/Precio': 90 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B07WDT29PJ', price: '22,99€' }],
    slug: 'shimano-fx-spinning-fishing-reel',
  },
  {
    title: 'Vicloon Kit de 21 señuelos para spinning',
    rating: 4.5,
    image: 'https://m.media-amazon.com/images/I/81pyRdk+hYL._AC_SL1500_.jpg',
    scores: { Construcción: 74, Nado: 76, Veracidad: 70, Lance: 78, 'Calidad/Precio': 95 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0FVSYNCBT', price: '12,49€' }],
    slug: 'vicloon-kits-de-seuelos-pescakits-de-seuelos-artificialeskits-de-seuelos-pesca-a',
  },
  {
    title: '100 Plomos de Pesca con Caja (0.4g–1.5g)',
    rating: 4.0,
    image: 'https://m.media-amazon.com/images/I/71D0sjWuwlL._AC_UL320_.jpg',
    scores: { Construcción: 72, Variedad: 85, Utilidad: 82, Precio: 96, 'Calidad/Precio': 93 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0FJ2GQ8GX', price: '6,59€' }],
    slug: '100-piezas-plomos-de-pesca-set-con-caja-04g05g06g08g1g12g15g-plomos-en-forma-de-',
  },
  {
    title: 'Shimano Vengeance CX 2.40m 10-35g — Caña calidad-precio',
    rating: 4.5,
    image: 'https://m.media-amazon.com/images/I/41L7cdhjPsL._AC_SX679_.jpg',
    scores: { Construcción: 86, Acción: 88, Lance: 90, Sensibilidad: 84, 'Calidad/Precio': 88 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B08K3H1HCK', price: '44,99€' }],
    slug: 'shimano-vengeance-cx---caa-spinning-240m-10-35g',
  },
  {
    title: 'Mitchell MX1 4000 — Carrete con 1.400+ valoraciones',
    rating: 4.3,
    image: 'https://m.media-amazon.com/images/I/812hiRdK1TL._AC_SX679_.jpg',
    scores: { Construcción: 80, Suavidad: 82, Frenado: 78, Resistencia: 76, 'Calidad/Precio': 90 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B09DGRP6VD', price: '27,66€' }],
    slug: 'mitchell-mx1---carrete-spinning-4000',
  },
  {
    title: 'Realure Juego de 3 señuelos multiarticulados',
    rating: 4.0,
    image: 'https://m.media-amazon.com/images/I/71fS25OXPzL._AC_SL1500_.jpg',
    scores: { Construcción: 87, Nado: 86, Veracidad: 90, Lance: 76, 'Calidad/Precio': 86 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0CJR762ZX', price: '13,99€' }],
    slug: 'realure-juego-de-3-seuelos-multiarticulados-para-lucio-de-15-cm-23-cm-30-cm-con-',
  },
  {
    title: 'Rapala-Mini alicates multiusos para pesca',
    rating: 4.2,
    image: 'https://ae-pic-a1.aliexpress-media.com/kf/Sa4f6cc3376cf444a948a735099badecbU.jpg',
    scores: { Construcción: 78, Utilidad: 88, Tamaño: 84, Precio: 90, 'Calidad/Precio': 88 },
    stores: [{ name: 'AliExpress', url: 'https://s.click.aliexpress.com/s/pyFri10M6ltAv61YZY9TfrxiDaaFXRreuZWJMeLtD8jig1wPxn51K2eq59ds8iT5Wl5L3w5KJyrl7SjOO3B0oJ0Xjwnc7n8AQA7gf5qnT4sCyU05LNms9JvyWQNFHNKtzBcoBpSguMg3UBR1FOODkmGTloXosMhqhnKgzzuJPYPxewVvzupiAiKSJA5SK0iQRxmaQ7UPG0AP2HC7uLitVpvXIfjMl7RnsnN7B8FrGfP9TWP7emQeaXV90Bp9fLEiLeKHsRf9R2jgKD32Axm5na4bRJdkhGVyv3GcDgMjmYrrZWinWctR9gnPwA4mNqlH6aMXaplzc5lv9K9pTPM0h4bmNLeKlEMC3gqqUBuchOPIYvjzY09aJgoBbVsNe1za4MdLkfO9Xk1ECsPbqfJLdZg3Xek2kTghaBmlafPlhQkvnR1LTFqcDKMh2yxOlYMCx67Ut72FhvMJumzhV5OgiHbHDpiLCGnX6HY1bbWAwsyhAr0syncLQN9NnWj6tU8WGEXXl8W842xKVjhvXL5IhPwMEjXrdOSDkEWzLp7ZW6kX1hPb3w9mBlczq0oXQoqwiLA0PvbIlnJVscokrLaS9zzV3syB6ILbbKuaKmPnJAHmewaXIVBb9Oa5lJMNj2P6WTNfsTbSFHvsZOCZrf0LOjB75tHQMp8UZJfLpLhzj8ehWw5REu51KNBak5aiGJDCkb8oQddkUUhDzxikfvwSbzHEMqSB4Y2bMlimGkc1Urd5Z6NXx1ONj6sn0LZjoW4TEt5NqEKVbsGqpRqIENmi2NMmiAHAv4D2jpbDtxnjyFDUzARQ8msjewMz1peNlu1IJ5QH91BW0xcryFf4m2iGLoQRN9rE9Oo833c4A71BWTWenw8M1hp6zPRhdYzfGyxbRpLljF7I8JNpPYs4ZaXdogwehzbwxDtnz7kka9K5XUCorESUQUSueR4E5emLI8T9Ze3Zize2IINTSAW72r7mAqJvmwibvVtKkrYFGy55PTrri4bF2sehvtH4rFxe19sUUpxO5EMs', price: '5,99€' }],
    slug: 'rapala-mini-alicates-para-seueloscontrolador-de-peces-juego-para-pesca-alicates-_aliexpress',
  },
  {
    title: 'Abu Garcia ORRA Predator — Caña Spinning premium',
    rating: 4.4,
    image: 'https://m.media-amazon.com/images/I/41TT8zficTL._AC_SL1500_.jpg',
    scores: { Construcción: 88, Acción: 88, Lance: 90, Sensibilidad: 86, 'Calidad/Precio': 82 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0DFRJRN6X', price: '50,39€' }],
    slug: 'abu-garcia-orra-predator-spinning-rod---premium-caa-de-pescar-para-los-pescadore',
  },
  {
    title: 'Mitchell MX2 4000 — Carrete de agua salada',
    rating: 4.5,
    image: 'https://m.media-amazon.com/images/I/716e1cd7CzL._AC_SL1500_.jpg',
    scores: { Construcción: 86, Suavidad: 84, Frenado: 84, Resistencia: 86, 'Calidad/Precio': 84 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0CDLY1JP7', price: '44,49€' }],
    slug: 'mitchell-carrete-giratorio-de-agua-salada-mx2-el-carrete-de-pesca-de-mar-ideal-p',
  },
  {
    title: 'Rapala Original Floating Minnow 9cm',
    rating: 4.7,
    image: 'https://m.media-amazon.com/images/I/71ihrIlYsML._AC_SX679_.jpg',
    scores: { Construcción: 90, Nado: 95, Veracidad: 92, Lance: 80, 'Calidad/Precio': 92 },
    stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B001NXCBVY', price: '12,86€' }],
    slug: 'rapala-original-floating-minnow-9cm---seuelo-de-pesca',
  },
]

const badges: Record<string, { badge?: string; badgeColor?: string }> = {
  0: { badge: 'Económica', badgeColor: '#EF4444' },
  1: { badge: 'Económica', badgeColor: '#EF4444' },
  2: { badge: 'Recomendada', badgeColor: '#F59E0B' },
  4: { badge: 'Mejor elección', badgeColor: '#00D4FF' },
  5: { badge: 'Calidad-precio', badgeColor: '#22C55E' },
  8: { badge: 'Gama alta', badgeColor: '#6366F1' },
  9: { badge: 'Gama alta', badgeColor: '#6366F1' },
  10: { badge: 'Recomendada', badgeColor: '#F59E0B' },
}

const productsData = JSON.stringify(products.map((p, i) => ({ ...p, ...(badges[i] || {}) })))

const content = [
  'Vas a una tienda a comprar tu primera caña y en diez minutos tienes un marrón encima: cañas de 2 metros y de 4, carretes de 1000 a 8000, señuelos que flotan, que se hunden, que vibran… Si no pescaste nunca con alguien que te lo explique, es normal no saber por dónde empezar.',
  '',
  'Este es el kit que le prepararía a un amigo que quiere empezar a pescar este año. Sin humos, sin pagar de más, con material que funciona de verdad y que no te vas a arrepentir de comprar. Todo lo que hay aquí está publicado ahora mismo en PesCatch con el mejor precio que he encontrado.',
  '',
  '## Para los que tienen prisa',
  '',
  'Si quieres empezar a pescar ya con un presupuesto cerrado:',
  '',
  '- **Kit básico (menos de 80€):** la caña **Abu Garcia Tormentor2** con el carrete **Shimano FX** y el kit de señuelos **Vicloon**. Con eso pescas el primer mes sin problemas.',
  '- **Kit calidad-precio (unos 100€):** la caña **Shimano Vengeance CX** con el carrete **Mitchell MX1** (1.400+ valoraciones) y los señuelos **Realure**. Es el conjunto que recomiendo a casi todo el mundo.',
  '- **Kit para agua salada (unos 95€):** la caña **Abu Garcia ORRA Predator** con el carrete **Mitchell MX2**. Si tu plan es pescar en el mar de verdad, no pierdas el tiempo con material de río.',
  '',
  'Y el **Rapala Original Floating Minnow** es el señuelo que no puede faltar en ninguna caja, da igual tu nivel.',
  '',
  '---',
  '',
  '## Kit básico: la caña, el carrete y los señuelos para tu primer mes',
  '',
  'Si nunca has pescado, no necesitas gastar 300€. Necesitas un conjunto equilibrado en el que la caña y el carrete se lleven bien, y señuelos de sobra para experimentar sin que duela cuando pierdas uno en una rama.',
  '',
  '### La caña: Abu Garcia Tormentor2 2.40m 10-30g',
  '',
  '<!--PRODUCT_IMG:1-->',
  '',
  'Una caña de spinning de 2,40 metros que soporta cebos de 10 a 30 gramos. Ese rango es el más versátil que existe: te vale para lanzar una cucharilla de 12g, un minnow de 9cm o un vinilo en un estanque. Y la marca, Abu Garcia, tiene un historial que no se discute.',
  '',
  'Es una caña que perdona: no es tan sensible como una de gama alta, pero tampoco se te va a romper el primer día que la pises con la punta clavada en el maletero. Para aprender, es la elección correcta.',
  '',
  '- **Longitud:** 2.40m | **Lances:** 10-30g | **Acción:** media-rápida',
  '- Perfecta para spinning en río, embalse y costa con señuelos ligeros',
  '- **Precio:** 34,99€',
  '',
  '### El carrete: Shimano FX 2500',
  '',
  '<!--PRODUCT_IMG:2-->',
  '',
  'Un carrete de tamaño 2500 es el que monta todo el mundo cuando empieza con spinning ligero: no es demasiado grande para la mano ni demasiado pequeño para aguantar un pez decente. El Shimano FX es de los más vendidos de su rango por una razón: funciona y es barato.',
  '',
  'No tiene los materiales premium de los carretes de 100€, pero para lanzar, recoger y enganchar con cabeza no se nota la diferencia. Y Shimano es Shimano: los recambios y el servicio existen en toda Europa.',
  '',
  '- **Tamaño:** 2500 | **Capacidad:** suficiente para trenza de 0.16mm',
  '- Frenado trasero fácil de ajustar con la mano húmeda',
  '- **Precio:** 22,99€',
  '',
  '### Los señuelos: Vicloon kit de 21 piezas',
  '',
  '<!--PRODUCT_IMG:3-->',
  '',
  'Cuando empiezas, pierdes señuelos. Se quedan en las ramas, en las algas, en el fondo de un río que nunca te devuelve nada. Por eso el primer kit no tiene que ser de señuelos de marca a 15€ la unidad, sino un lote variado para aprender qué colores y qué movimientos funcionan en tu zona.',
  '',
  'El kit de Vicloon trae 21 señuelos de distintos tipos y tamaños por 12,49€. No esperes la calidad de construcción de un Rapala, pero para el primer mes es justo lo que necesitas: variedad para aprender sin vaciar la cartera.',
  '',
  '- **Contenido:** 21 señuelos variados (cucharillas, minnows, spinners)',
  '- **Precio:** 12,49€ | Ideal para probar sin miedo',
  '',
  '### Los plomos: 100 unidades con caja por 6,59€',
  '',
  '<!--PRODUCT_IMG:4-->',
  '',
  'Parecen un detalle, pero cuando te toca pescar a fondo y no tienes un plomo de 0,8g, te acuerdas. Este lote trae 100 plomos de 0.4g a 1.5g con su caja, que es el rango que usas para spinning y pesca a fondo ligera. De esos que no piensas y compras de nuevo cuando se acaben.',
  '',
  '- **Contenido:** 100 plomos (0.4g–1.5g) con caja',
  '- **Precio:** 6,59€',
  '',
  'Con estos cuatro elementos estás pescando el primer fin de semana. Punto.',
  '',
  '---',
  '',
  '## Kit calidad-precio: pescar en serio sin arruinarte',
  '',
  'Si ya has pescado alguna vez con el material de un amigo y sabes que esto te va a enganchar, merece la pena subir un peldaño. Este es el conjunto que recomiendo a casi todo el mundo: caña y carrete que te duran años y aguantan el día a día.',
  '',
  '### La caña: Shimano Vengeance CX 2.40m 10-35g',
  '',
  '<!--PRODUCT_IMG:5-->',
  '',
  'La Vengeance CX es la caña de entrada de Shimano, pero no parece de entrada cuando la tienes en la mano: blank de carbono con una acción rápida que lanza con ganas y transmite las picadas con claridad. Soporta hasta 35g, así que también puedes usarla para spinning medio sin que sufra.',
  '',
  'Es la caña que recomiendo a quien quiere notar la diferencia respecto al material "de todo a cien" desde el primer lance.',
  '',
  '- **Longitud:** 2.40m | **Lances:** 10-35g | **Carbono**',
  '- **Precio:** 44,99€',
  '',
  '### El carrete: Mitchell MX1 4000',
  '',
  '<!--PRODUCT_IMG:6-->',
  '',
  'Más de 1.400 valoraciones en Amazon y casi todas positivas. El Mitchell MX1 es de esos carretes que han hecho historia: suave, fiable y con un precio que no parece real para lo que ofrece. En 4000 tienes capacidad de sobra para pescar en río, embalse y hasta algunas modalidades de costa.',
  '',
  'Es la pareja ideal de la Vengeance CX y, probablemente, la mejor compra calidad-precio de toda esta lista.',
  '',
  '- **Tamaño:** 4000 | **Sistema:** giro de 6+1 rodamientos',
  '- **Precio:** 27,66€',
  '',
  '### Los señuelos: Realure juego de 3 multiarticulados',
  '',
  '<!--PRODUCT_IMG:7-->',
  '',
  'Los señuelos multiarticulados son una apuesta segura para depredadores: su movimiento ondulado con juntas de alambre es de los que más picadas provocan. El pack de Realure trae tres tamaños (15, 23 y 30cm) para cubrir desde el lucio de río hasta la lubina grande de escollera.',
  '',
  '- **Contenido:** 3 señuelos multiarticulados (15/23/30cm)',
  '- **Precio:** 13,99€',
  '',
  '### Los alicates: Rapala-Mini multiusos',
  '',
  '<!--PRODUCT_IMG:8-->',
  '',
  'Cuando claves un señuelo triple en la mano de un lucio, lo último que quieres es no tener un alicate a mano. Este mini alicate de Rapala es pequeño, va en el bolsillo y sirve para soltar anzuelos, cortar hilo y abrir los split rings. Por 5,99€ no deberías salir de casa sin él.',
  '',
  '- **Uso:** soltar anzuelos, cortar línea, abrir anillas',
  '- **Precio:** 5,99€ (AliExpress)',
  '',
  'Total del kit: unos 92€. Diez veces menos que empezar a lo bruto y con material que no te va a fallar.',
  '',
  '---',
  '',
  '## Kit para agua salada: cuando la pesca va en serio',
  '',
  'Si tu plan es pescar en el mar —escollera, puerto, playa con señuelo— no pierdas tiempo con material pensado para agua dulce: la sal se come los carretes baratos y las cañas blandas no lanzan lo que necesitas. Este kit está pensado para el agua salada de verdad.',
  '',
  '### La caña: Abu Garcia ORRA Predator',
  '',
  '<!--PRODUCT_IMG:9-->',
  '',
  'La ORRA Predator de Abu Garcia es una caña de spinning pensada para depredadores, con un blank que aguanta el castigo del agua salada y una acción rápida para lances largos desde la escollera. Es la caña que recomiendo si vives cerca de la costa y vas a pescar con señuelos de spinning medio-pesado.',
  '',
  '- **Longitud:** 2.70m aprox. | **Diseño:** agua salada',
  '- **Precio:** 50,39€',
  '',
  '### El carrete: Mitchell MX2 4000 de agua salada',
  '',
  '<!--PRODUCT_IMG:10-->',
  '',
  'El MX2 es la versión marinada del famoso MX1: materiales y tratamientos específicos para que la sal no lo corroa tras cada jornada. Si vas a pescar en el mar, esto no es un capricho, es una necesidad: un carrete de agua dulce te dura una temporada en la costa, este te dura años.',
  '',
  '- **Tamaño:** 4000 | **Específico:** agua salada',
  '- **Precio:** 44,49€',
  '',
  'Con la ORRA Predator y el MX2 tienes un conjunto de mar serio por menos de 95€ que no tiene nada que envidiar a combos de el doble de precio.',
  '',
  '---',
  '',
  '## El señuelo que no puede faltar: Rapala Original Floating Minnow',
  '',
  '<!--PRODUCT_IMG:11-->',
  '',
  'Hay señuelos que nacen, se copian y se siguen copiando porque funcionan. El Rapala Original Floating Minnow es el más copiado de la historia: flota y con una recogida lenta baja a un metro, cuando paras sube a superficie. Ese movimiento es oro para una lubina en la rompiente.',
  '',
  'Lleva décadas llenando cajas de pescadores de medio mundo. Por 12,86€, es la mejor inversión de toda esta lista: da igual el kit que elijas, este señuelo no puede faltar.',
  '',
  '- **Tipo:** flotante | **Tamaño:** 9cm',
  '- **Precio:** 12,86€ | El más vendido de su categoría',
  '',
  '---',
  '',
  '## Errores que todos cometemos al empezar (y cómo evitarlos)',
  '',
  'Aprendí esto a base de quemarme, así que te lo dejo por escrito:',
  '',
  '- **Comprar el carrete más grande "por si acaso".** Un 2500/3000 para spinning ligero es suficiente. Un 8000 con una caña de 10-30g es un desastre imposible de lanzar.',
  '- **No mirar el rango de lances de la caña.** Si la caña es de 10-30g y montas una cucharilla de 50g, la punta salta. Mira siempre ese número antes de comprar señuelos.',
  '- **Llevar la trenza sin líder.** La trenza se corta con las rocas y se la comen los peces con dientes. Un trozo de monofilamento o fluorocarbono de 30-50cm al final salva la jornada.',
  '- **No llevar alicates.** Hasta que no sacas un triple del dedo de un amigo, no entiendes por qué. Son 6€, llévalos siempre.',
  '',
  '---',
  '',
  '## FAQ',
  '',
  '### ¿Caña y carrete se compran por separado?',
  '',
  'Sí, y en PesCatch los tienes así. Comprarlos por separado te permite elegir un carrete de mejor calidad que los que montan los conjuntos baratos, que suelen ser lo más flojo del pack. La caña y el carrete de los kits de aquí los hemos combinado para que se lleven bien en tamaño y lances.',
  '',
  '### ¿Qué tamaño de carrete necesito para empezar?',
  '',
  'Un 2500 para spinning ligero de río y embalse, y un 4000 si vas a pescar también en costa o con señuelos más pesados. El Shimano FX 2500 del kit básico y el Mitchell MX1 4000 del kit calidad-precio cubren el 95% de las situaciones del que empieza.',
  '',
  '### ¿Me vale el mismo material para agua dulce y agua salada?',
  '',
  'Para estrenarte, sí, pero si tu plan es el mar, hazte con material específico cuanto antes: la sal corroe los rodamientos de los carretes de agua dulce y acaba con ellos en una temporada. El Mitchell MX2 del kit de mar está diseñado para aguantar eso.',
  '',
  '### ¿Trenza o monofilamento para empezar?',
  '',
  'Trenza para el carrete (más fina, más distancia, más sensibilidad) y un líder de monofilamento o fluorocarbono al final. No hace falta que sea de marca cara: una trenza de 0.12-0.16mm y un líder de 0.25-0.30mm es una combinación que funciona en casi todo.',
  '',
  '### ¿Puedo comprar el material que sale en este artículo en Amazon?',
  '',
  'Sí, todos los productos están enlazados directamente a Amazon y AliExpress con el mejor precio encontrado y publicado en PesCatch. Pulsa "Comprar" en cualquier producto para verlo en la tienda.',
  '',
  '## Conclusión',
  '',
  'Empezar a pescar no tiene por qué ser caro ni un lío. Con el **kit básico** (Tormentor2 + Shimano FX + Vicloon + plomos) estás pescando el primer fin de semana por menos de 80€. Si ya pescaste prestado y sabes que esto va contigo, sube al **kit calidad-precio** (Vengeance CX + Mitchell MX1 + Realure). Y si tu plan es el mar, el **kit de agua salada** (ORRA Predator + Mitchell MX2) te prepara de verdad por menos de 95€.',
  '',
  'Añade un **Rapala Minnow** a cualquier kit y ya tienes la temporada resuelta. Nos vemos en el agua.',
  '',
].join('\n')

const fullContent = content + `\n\n<!-- PRODUCTS_DATA: ${productsData} -->`

async function main() {
  const post = await createPost({
    title: 'Kit completo para empezar a pescar 2026: caña, carrete y señuelos para tu primera jornada',
    slug: 'kit-completo-empezar-pescar-2026',
    excerpt: 'Kit completo para empezar a pescar en 2026: caña y carrete combinados por presupuesto (básico, calidad-precio y agua salada), señuelos recomendados y los errores de principiante que puedes evitar. Todo con el mejor precio actualizado en PesCatch.',
    content: fullContent,
    featuredImage: products[4].image,
    author: 'PesCatch',
    category: 'Principiante',
    tags: ['kit pesca principiante', 'kit completo pesca', 'caña y carrete', 'empezar a pescar', 'material pesca barato'],
    relatedAsins: ['B0DLGKNG9P', 'B07WDT29PJ', 'B0FVSYNCBT', 'B0FJ2GQ8GX', 'B08K3H1HCK', 'B09DGRP6VD', 'B0CJR762ZX', 'B0DFRJRN6X', 'B0CDLY1JP7', 'B001NXCBVY'],
    status: 'published',
    metaTitle: 'Kit completo para empezar a pescar 2026: caña, carrete y señuelos recomendados',
    metaDescription: 'El kit de pesca para empezar en 2026: caña + carrete + señuelos combinados por presupuesto. Guía con precios actualizados, errores de principiante y FAQ. Empezar a pescar sin pagar de más.',
    focusKeyword: 'kit pesca principiante',
  })
  console.log('✅ Post creado:', post.slug, '| id:', post.id)
}

main().catch((err) => {
  console.error('Error:', err)
  process.exit(1)
})
