import { getDb, initSchema } from '../src/lib/db'

async function seedBlogPost() {
  const db = getDb()
  await initSchema()

  const slug = 'mejores-canas-spinning-2026'
  const now = new Date().toISOString()

  const content = [
    'Elegir la caña de spinning adecuada puede marcar la diferencia entre una jornada de pesca memorable y una frustrante. Hemos probado y comparado los modelos más destacados del mercado para ayudarte a encontrar la caña perfecta según tu presupuesto y estilo de pesca.',
    '',
    '## Para los que tienen prisa',
    '',
    '**Daiwa Morethan Branzino AGS** es la mejor caña de spinning del mercado sin discusión. Si buscas calidad-precio, el **Hart Bloody Marine UL** te sorprenderá. Para empezar con garantías, el **Daiwa Legalis Seabass** es imbatible en su rango. Y si tu presupuesto es ajustado, el **Daiwa Ninja Spinning** cumple sobradamente.',
    '',
    '---',
    '',
    '## 1. Daiwa Morethan Branzino AGS — La mejor en general',
    '',
    'La **Daiwa Morethan Branzino AGS** es, sin duda, la caña de spinning más avanzada que puedes comprar. Fabricada con carbono SVF Compile-X Nanoplus, pesa apenas 129 gramos y monta las exclusivas anillas AGS de carbono, que son un 30% más ligeras que las convencionales.',
    '',
    'Su acción de punta permite trabajar todo tipo de señuelos con una precisión milimétrica. Desde vinilos de 5 gramos hasta paseantes de 30 gramos, la caña responde con una sensibilidad extrema. Notarás cada vibración del fondo marino en tu mano.',
    '',
    '- **Peso:** 129g | **Longitud:** 240cm | **Acción:** 14-42g',
    '- Ideal para spinning medio y ligero en costa y embarcación',
    '- Perfecta para lubina, dorada, anjova, palometón y bonito',
    '- Lo mejor: Sensibilidad absoluta, peso pluma, construcción premium',
    '',
    'Ideal para el pescador experimentado que busca lo mejor sin compromisos.',
    '',
    '---',
    '',
    '## 2. Shimano Dialuna Inshore S100MH — Gama alta versátil',
    '',
    'La **Shimano Dialuna Inshore** representa el equilibrio perfecto entre potencia y ligereza. Con 176 gramos y 305 cm de longitud, está diseñada para lances largos en costa con señuelos de 10 a 50 gramos. Su tecnología Spiral X Plus y Hi-Power X eliminan torsiones y proporcionan una acción ultra-rápida.',
    '',
    'Es una caña que aguanta bien el agua salada y ofrece una potencia brutal en el tercio inferior para clavar y controlar peces grandes.',
    '',
    '- **Peso:** 176g | **Longitud:** 305cm | **Acción:** 10-50g',
    '- Ideal para spinning pesado y shore jigging',
    '- Perfecta para lubinas grandes, bacoretas y depredadores marinos',
    '- Lo mejor: Potencia, alcance en el lance, construcción robusta',
    '',
    'Recomendada para pescadores que buscan una caña larga y potente para surfcasting ligero o spinning de orilla.',
    '',
    '---',
    '',
    '## 3. Hart Bloody Marine UL 84 — La mejor calidad-precio',
    '',
    'La **Hart Bloody Marine UL** es un auténtico best-seller en España. Por unos 150€ recibes una caña de carbono de 40 toneladas con anillas Fuji K Alconite y portacarretes Fuji Skeleton. Su acción progresiva de 5 a 28 gramos la hace perfecta para spinning ligero y ultraligero.',
    '',
    'Es sorprendentemente sensible para su precio, con un blank que transmite cada picada. Perfecta para pescar desde roca o espigón con señuelos ligeros.',
    '',
    '- **Peso:** 130g | **Longitud:** 255cm | **Acción:** 5-28g',
    '- Ideal para spinning ligero y rockfishing',
    '- Perfecta para lubina, serrátidos, dorada y pesca fina',
    '- Lo mejor: Relación calidad-precio brutal, ligereza, acción progresiva',
    '',
    'La elección inteligente para el pescador que quiere calidad sin gastar una fortuna.',
    '',
    '---',
    '',
    '## 4. Daiwa Legalis Seabass 902HFS — La mejor para empezar',
    '',
    'La **Daiwa Legalis Seabass** es la puerta de entrada al spinning de calidad. Por unos 100€ tienes una caña fabricada en carbono HVF con anillas Fuji O-Ring y portacarretes Fuji DPS. Pesada pero robusta, ofrece una acción rápida de punta que facilita el aprendizaje.',
    '',
    'Aguanta bien la salinidad, los golpes y el uso intensivo. Es una caña que te durará años si la cuidas, y te permitirá progresar sin sentir que necesitas cambiar de equipo.',
    '',
    '- **Peso:** 181g | **Longitud:** 274cm | **Acción:** 14-42g',
    '- Ideal para iniciación al spinning de costa',
    '- Perfecta para lubina, anjova, palometón y pesca variada',
    '- Lo mejor: Precio contenido, durabilidad, versatilidad',
    '',
    'Para el que empieza o quiere una caña de batalla para usar sin miedo.',
    '',
    '---',
    '',
    '## 5. Daiwa Ninja Spinning — La más económica que funciona',
    '',
    'La **Daiwa Ninja Spinning** demuestra que no hace falta gastar 200€ para tener una caña decente. Por unos 50€, recibes una caña de carbono con acción progresiva fuerte, anillas de óxido de aluminio y portacarretes de grafito. Pesa 138 gramos y está disponible en múltiples medidas.',
    '',
    'No esperes la sensibilidad de una caña de 600€, pero para pescar con vinilos, cucharillas y señuelos de hasta 30 gramos cumple perfectamente. Es la caña ideal para tener siempre en el coche por si surge la oportunidad de pescar.',
    '',
    '- **Peso:** 138g | **Longitud:** 240cm | **Acción:** 10-30g',
    '- Ideal para pescadores ocasionales o presupuesto ajustado',
    '- Perfecta para principiantes, pesca en río y embalse',
    '- Lo mejor: Precio imbatible, polivalente, variedad de modelos',
    '',
    'La mejor opción si necesitas una caña funcional sin gastar casi nada.',
    '',
    '---',
    '',
    '## Tabla comparativa rápida',
    '',
    '**Daiwa Morethan Branzino AGS** — 651€ — 129g — Carbono SVF — Acción punta — ★★★★★',
    '**Shimano Dialuna Inshore** — ~350€ — 176g — Carbono Spiral X — Acción rápida — ★★★★☆',
    '**Hart Bloody Marine UL** — 159€ — 130g — Carbono 40T — Acción progresiva — ★★★★☆',
    '**Daiwa Legalis Seabass** — ~100€ — 181g — Carbono HVF — Acción punta — ★★★★☆',
    '**Daiwa Ninja Spinning** — ~50€ — 138g — Carbono — Acción progresiva — ★★★☆☆',
    '',
    '---',
    '',
    '## Cómo elegir tu caña de spinning',
    '',
    '### 1. Define tu presupuesto',
    'El dinero que estés dispuesto a invertir marcará las tecnologías a las que puedas acceder. Con 50-100€ tendrás una caña funcional. De 100-200€ encuentras calidad-precio excelente. A partir de 300€ entras en el terreno de la alta gama con carbono de módulo ultralto y componentes premium.',
    '',
    '### 2. Elige la acción y potencia adecuadas',
    'El rango de gramos de la caña debe coincidir con los señuelos que vas a usar. Para spinning ligero (vinilos, pequeños paseantes) busca acciones de 5-28g. Para spinning medio (jigs, popping) busca 14-50g. Para pesado (shore jigging) necesitas más de 40g.',
    '',
    '### 3. Longitud según tu escenario',
    'Cañas de 210-240cm ideales para roca y espacios reducidos. Cañas de 250-300cm perfectas para playa y lances largos. Las cañas más largas ofrecen más distancia pero pesan más y son menos manejables en espacios cerrados.',
    '',
    '### 4. Anillas y portacarretes',
    'Las anillas Fuji (K, Alconite, SiC) son el estándar de calidad. Las anillas de óxido de aluminio son correctas para gama baja. El portacarretes debe ser firme y de material resistente a la corrosión.',
    '',
    '### 5. Peso de la caña',
    'Una caña ligera reduce la fatiga en jornadas largas. El carbono de alto módulo permite cañas más ligeras sin perder potencia. Busca siempre el menor peso posible dentro de tu presupuesto.',
    '',
    '---',
    '',
    '## Preguntas frecuentes',
    '',
    '### ¿Qué diferencia hay entre una caña de spinning y una de surfcasting?',
    'Las cañas de spinning son más cortas (210-300cm) y están diseñadas para lanzar señuelos artificiales. Las de surfcasting son más largas (350-500cm) y se usan para lanzar plomos y cebo natural a larga distancia.',
    '',
    '### ¿Qué carrete le pongo a mi caña de spinning?',
    'Para cañas de acción ligera (hasta 28g) usa carretes tamaño 1000-2500. Para acción media (10-42g) usa tamaño 3000-4000. La caña y el carrete deben estar equilibrados: sujeta la caña con el carrete montado y debe sentirse equilibrada, no caer hacia la punta ni hacia el mango.',
    '',
    '### ¿Las cañas de spinning valen para agua salada?',
    'Sí, pero deben tener componentes resistentes a la corrosión. Busca anillas Fuji, portacarretes de aluminio o acero inoxidable, y blanks sellados. Todas las cañas de esta guía valen para agua salada con los cuidados adecuados (aclarar con agua dulce después de usar).',
    '',
    '### ¿Merece la pena gastar 600€ en una caña?',
    'Depende de tu nivel. Si pescas 3-4 veces al año, no. Si pescas cada semana y quieres sentir cada picada, sí. La diferencia entre una caña de 150€ y una de 600€ está en la sensibilidad, el peso y la precisión en el lance.',
    '',
    '---',
    '',
    '## Veredicto final',
    '',
    'La **Daiwa Morethan Branzino AGS** es, sin duda, la mejor caña de spinning que puedes comprar en 2026. Su combinación de ligereza, sensibilidad y construcción es imbatible. Pero la realidad es que la mayoría de los pescadores no necesitan una caña de 650€.',
    '',
    'Si pescas con frecuencia, el **Hart Bloody Marine UL** te dará el 85% de la experiencia por el 25% del precio. Y si estás empezando, el **Daiwa Legalis Seabass** o el **Ninja Spinning** te permitirán disfrutar sin arruinarte.',
    '',
    'Elige según tu presupuesto y frecuencia de pesca. Cualquier caña de esta lista te hará disfrutar más de tus jornadas de spinning.',
  ].join('\n')

  const productsData = JSON.stringify([
    {
      asin: 'B077RLWCBR',
      title: 'Daiwa Morethan Branzino AGS',
      price: '651€',
      rating: 4.8,
      image: 'https://m.media-amazon.com/images/I/41XUZO4rM1L._AC_SX679_.jpg',
      scores: { Construcción: 98, Sensibilidad: 99, Ligereza: 98, 'Calidad/Precio': 60, 'Resistencia salada': 95 },
    },
    {
      asin: 'B0BRBVJ91D',
      title: 'Shimano Dialuna Inshore S100MH',
      price: '349€',
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/41qSMFgbOPL._AC_SX679_.jpg',
      scores: { Construcción: 90, Sensibilidad: 88, Ligereza: 85, 'Calidad/Precio': 75, 'Resistencia salada': 92 },
    },
    {
      asin: 'B08VHVLWJP',
      title: 'Hart Bloody Marine UL 84',
      price: '159€',
      rating: 4.5,
      image: 'https://m.media-amazon.com/images/I/31ELwLq68lL._AC_SX679_.jpg',
      scores: { Construcción: 82, Sensibilidad: 88, Ligereza: 90, 'Calidad/Precio': 95, 'Resistencia salada': 78 },
    },
    {
      asin: 'B09812WXBY',
      title: 'Daiwa Legalis Seabass 902HFS',
      price: '99€',
      rating: 4.3,
      image: 'https://m.media-amazon.com/images/I/31+1yPRjRGL._AC_SX679_.jpg',
      scores: { Construcción: 78, Sensibilidad: 72, Ligereza: 70, 'Calidad/Precio': 88, 'Resistencia salada': 80 },
    },
    {
      asin: 'B096W4WKXB',
      title: 'Daiwa Ninja Spinning',
      price: '49€',
      rating: 4.0,
      image: 'https://m.media-amazon.com/images/I/31LctPFrprL._AC_SX679_.jpg',
      scores: { Construcción: 65, Sensibilidad: 55, Ligereza: 72, 'Calidad/Precio': 92, 'Resistencia salada': 60 },
    },
  ])

  const fullContent = content + `\n\n<!-- PRODUCTS_DATA: ${productsData} -->`

  const existing = await db.execute({
    sql: 'SELECT id FROM posts WHERE slug = ?',
    args: [slug],
  })

  if (existing.rows.length > 0) {
    const id = existing.rows[0].id as string
    await db.execute({
      sql: `UPDATE posts SET title = ?, excerpt = ?, content = ?, featuredImage = ?,
        author = ?, category = ?, tags = ?, relatedAsins = ?, updatedAt = ?
        WHERE id = ?`,
      args: [
        'Las 5 mejores cañas de spinning de 2026: comparativa y guía de compra',
        '¿Buscas una caña de spinning? Analizamos y comparamos los mejores modelos de 2026: Daiwa Morethan Branzino AGS, Shimano Dialuna, Hart Bloody Marine UL, Daiwa Legalis Seabass y Ninja Spinning.',
        fullContent,
        '',
        'PesCatch',
        'Cañas',
        JSON.stringify(['cañas spinning', 'spinning', 'cañas pesca', 'rankings', 'guias compra']),
        JSON.stringify(['B077RLWCBR', 'B0BRBVJ91D', 'B08VHVLWJP', 'B09812WXBY', 'B096W4WKXB']),
        now,
        id,
      ],
    })
    console.log(`✅ Blog post updated: ${slug}`)
  } else {
    await db.execute({
      sql: `INSERT INTO posts (id, title, slug, excerpt, content, featuredImage, author, category, tags, relatedAsins, hidden, publishedAt, createdAt, updatedAt)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        `post_${Date.now()}`,
        'Las 5 mejores cañas de spinning de 2026: comparativa y guía de compra',
        slug,
        '¿Buscas una caña de spinning? Analizamos y comparamos los mejores modelos de 2026: Daiwa Morethan Branzino AGS, Shimano Dialuna, Hart Bloody Marine UL, Daiwa Legalis Seabass y Ninja Spinning.',
        fullContent,
        '',
        'PesCatch',
        'Cañas',
        JSON.stringify(['cañas spinning', 'spinning', 'cañas pesca', 'rankings', 'guias compra']),
        JSON.stringify(['B077RLWCBR', 'B0BRBVJ91D', 'B08VHVLWJP', 'B09812WXBY', 'B096W4WKXB']),
        0, now, now, now,
      ],
    })
    console.log(`✅ Blog post created: ${slug}`)
  }
}

seedBlogPost().catch(console.error)
