import { getDb, initSchema } from '../../src/lib/db'

// PROPÓSITO: Crear post "mejores-carretes-surfcasting-2026" (carretes de surfcasting solo Amazon/AliExpress, sin Decathlon).
// FECHA: 2026-08-13
// FECHA: El afiliado de Decathlon fue denegado → NO enlazar Decathlon en este post.

async function seedBlogPost() {
  const db = getDb()
  await initSchema()

  const slug = 'mejores-carretes-surfcasting-2026'
  const now = new Date().toISOString()

  const content = [
    'Elegir un carrete de surfcasting no es lo mismo que elegir uno de spinning. Aquí el protagonista es el lance largo: necesitas un carrete grande (de 5000 hacia arriba), con una bobina que deje salir el trenzado sin fricción y un freno que aguante la carrera de una lubina de concurso al otro lado. Y encima, todo eso tiene que sobrevivir a la sal.',
    '',
    'En esta guía he reunido los mejores carretes de surfcasting que puedes comprar hoy con precio real y verificado. Sin humo, sin precios inflados de catálogo: lo que pagas hoy.',
    '',
    '## Para los que tienen prisa',
    '',
    'Si tu presupuesto es serio y quieres un carrete que te dure toda la vida, el **Shimano Ultegra 14000 XSE** es lo mejor que puedes montar en una caña de 4.20m. El **PENN Surfblaster III** es el especialista en resistencia salada por menos de 150€. Y si buscas el mejor equilibrio entre precio y prestaciones, el **Daiwa Ninja LT 6000** es la compra más inteligente de la lista.',
    '',
    '---',
    '<!--PRODUCT_IMG:1-->',
    '',
    '## 1. Shimano Ultegra 14000 XSE — El rey del surfcasting',
    '',
    'El **Shimano Ultegra 14000 XSE** es la referencia del surfcasting moderno. Es el carrete que ves en manos de los que se toman en serio el lance en la playa, y no es por casualidad: aúna la tecnología Hagane de engranajes forjados en frío con el tratamiento CoreProtect, que hace que el interior aguante la corrosión salada mucho mejor que cualquier carrete de gama media.',
    '',
    'Su bobina larga de aluminio está diseñada para lances a distancia: el trenzado sale sin bajar fricción y el devanado es uniforme incluso con trenzados finos de 0.20mm. En las jornadas de playa, la diferencia frente a carretes más baratos se nota en que no tienes que "limpiar" el nido de viento cada dos lances.',
    '',
    'El freno de carbono alcanza los 20kg, suficiente para domar cualquier pez que muerda en la orilla. Y el recuperado, con su relación 4.3:1, te permite recoger el carrete pesado sin esfuerzo cuando el pez se acerca a la orilla.',
    '',
    '- **Tamaño:** 14000 | **Rodamientos:** 6+1 | **Recuperación:** 92cm | **Freno:** 20kg',
    '- Ideal para surfcasting de potencia media y pesada en playa',
    '- Perfecto para lubina, dorada, anjova, corvina y pesca de fondo a distancia',
    '- Lo mejor: Protección CoreProtect contra la sal, engranajes Hagane, bobina de lance',
    '',
    'Es una inversión, pero es de esos carretes que compras una vez. Si pescas el surfcasting cada semana, es la elección definitiva.',
    '',
    '---',
    '<!--PRODUCT_IMG:2-->',
    '',
    '## 2. PENN Surfblaster III — El especialista en resistencia salada',
    '',
    'PENN es sinónimo de pesca de mar, y el **Surfblaster III** es su apuesta para el surfcasting de rango medio. Monta 5+1 rodamientos de acero inoxidable y, lo más importante, un freno HT-100 de fibra de carbono sellado contra el agua: la arena y la sal no entran donde no deben.',
    '',
    'Su cuerpo de aluminio aguanta el maltrato de la playa y la bobina de lanzamiento largo está pensada para cañas de 4.20-4.50m. En cuanto al recuperado, es rápido y directo, sin juego, justo lo que necesitas para recoger trenzado a distancia.',
    '',
    'Donde el Surfblaster destaca sobre la competencia a este precio es en la fiabilidad en agua salada: puedes usarlo año tras año con un mínimo mantenimiento y no te va a dejar tirado. Es la opción preferida por muchos que pescan de roca y playa con cañas largas.',
    '',
    '- **Tamaño:** 4500-5000 | **Rodamientos:** 5+1 inox | **Freno:** HT-100 sellado | **Cuerpo:** aluminio',
    '- Ideal para surfcasting medio en playa, roca y embarcación',
    '- Perfecto para lubina, dorada, sargo, besugo y pesca variada de orilla',
    '- Lo mejor: Rodamientos inox, freno sellado, construcción a prueba de sal',
    '',
    'El mejor equilibrio entre precio y resistencia a la corrosión. Si el Ultegra se te escapa del presupuesto, este es tu carrete.',
    '',
    '---',
    '<!--PRODUCT_IMG:3-->',
    '',
    '## 3. Daiwa Ninja 23 LT 6000 — El mejor calidad-precio',
    '',
    'El **Daiwa Ninja 23 LT 6000** es la prueba de que no hace falta gastar 150€ para tener un carrete de surfcasting digno. La tecnología LT (Light & Tough) de Daiwa consigue un cuerpo ultraligero de solo 335 gramos sin sacrificar resistencia, algo que hace unos años era impensable por este precio.',
    '',
    'El rotor Air Rotor y el devanado con oscilación lenta hacen que el trenzado se asiente de forma uniforme en la bobina, lo que se traduce en menos nudos de viento en el lance. Es un carrete que trabaja especialmente bien con trenzados finos de surfcasting, entre 0.16mm y 0.22mm.',
    '',
    'El freno ATD (Automatic Tournament Drag) es progresivo y suave, ideal cuando pescas con cañas de acción de punta y no quieres que un tirón seco rompa el aparejo. Por debajo de 60€, no hay nada que le haga sombra.',
    '',
    '- **Tamaño:** 6000 | **Rodamientos:** 5+1 | **Peso:** 335g | **Freno:** ATD',
    '- Ideal para surfcasting ligero y medio, spinning pesado y lanzado',
    '- Perfecto para lubina, dorada, anjova y depredadores de costa',
    '- Lo mejor: Peso pluma, tecnología LT, freno ATD progresivo',
    '',
    'La compra más inteligente de toda la comparativa. Si empiezas en el surfcasting o no quieres arriesgar mucho dinero, este es el carrete.',
    '',
    '---',
    '<!--PRODUCT_IMG:4-->',
    '',
    '## 4. Mitchell MX2 — El aguante del agua salada por menos de 50€',
    '',
    'Mitchell es una marca histórica de la pesca española, y el **MX2** es su carrete de agua salada de entrada. Lo que lo hace interesante para el surfcasting es su relación calidad-precio brutal: por menos de 50€ tienes 5+1 rodamientos de acero inoxidable, un cuerpo de grafito reforzado y un diseño pensado para aguantar el mar.',
    '',
    'La bobina es lo suficientemente grande como para trabajar con cañas de 3.60m a 4.20m en surfcasting ligero, y el freno delantero es suave y regulable con precisión. No es un carrete para lances de 150 metros con plomos de 150 gramos, pero cumple sobradamente en pesca de orilla con plomos medios.',
    '',
    'Además, ahora mismo está a un 36% de descuento sobre su precio original, lo que lo convierte en una de las mejores ofertas de la lista.',
    '',
    '- **Tamaño:** 5000-6000 | **Rodamientos:** 5+1 inox | **Cuerpo:** grafito reforzado',
    '- Ideal para surfcasting ligero y pesca de orilla con plomos medios',
    '- Perfecto para dorada, lubina, sargo y pesca variada desde la orilla',
    '- Lo mejor: Rodamientos inox, precio de oferta, relación calidad-precio',
    '',
    'La opción recomendada si quieres un carrete de mar fiable sin gastar una fortuna y te beneficias de la rebaja actual.',
    '',
    '---',
    '<!--PRODUCT_IMG:5-->',
    '',
    '## 5. Shimano Sienna FG 4000 — El fiable para empezar',
    '',
    'El **Shimano Sienna FG** es el carrete más vendido de Shimano por una razón: es fiable, barato y fácil de mantener. En surfcasting ligero o como carrete de inicio para una caña de 3.60-3.90m, cumple de sobra, y su fama le precede: es el carrete que muchos pescadores veteranos tienen como segundo equipo.',
    '',
    'La tecnología Propulsion Line Management reduce los nudos de viento, el devanado es uniforme gracias a la oscilación lenta y el freno delantero de 8.5kg es más que suficiente para la pesca de orilla. No esperes la ligereza ni la suavidad de un carrete de gama alta, pero a este precio es difícil encontrar algo más recomendable para empezar.',
    '',
    'Su mayor ventaja es que lo encuentras en cualquier tienda y cualquier aparejador sabe arreglarlo. Para el que se está iniciando en el surfcasting, es la compra segura.',
    '',
    '- **Tamaño:** 4000 | **Rodamientos:** 3+1 | **Recuperación:** 82cm | **Freno:** 8.5kg',
    '- Ideal para surfcasting ligero de iniciación y spinning',
    '- Perfecto para principiantes, dorada, lubina y pesca variada',
    '- Lo mejor: Fiabilidad Shimano, precio imbatible, fácil mantenimiento',
    '',
    'El carrete perfecto para empezar a lanzar en la playa sin arriesgar dinero. Cuando le cojas el gusto, ya sabrás a qué quieres ascender.',
    '',
    '---',
    '<!--PRODUCT_IMG:6-->',
    '',
    '## 6. Daiwa Joinus 5000 — El más barato que funciona en el mar',
    '',
    'Cierro con el **Daiwa Joinus 5000**, el carrete de Daiwa para pesca marina más económico de la lista. Es la puerta de entrada a la marca japonesa por poco más de 30€, y aunque es básico, está bien construido para su precio.',
    '',
    'Su bobina es lo suficientemente amplia para el surfcasting ligero, el recuperado es aceptable y el cuerpo aguanta razonablemente bien la sal con un mantenimiento básico. No es un carrete para machacarlo con lances de potencia ni para usarlo toda la temporada en agua salada sin cuidado, pero como primer carrete de mar o como repuesto de emergencia, cumple.',
    '',
    '- **Tamaño:** 5000 | **Rodamientos:** 3+1 | **Cuerpo:** grafito',
    '- Ideal para surfcasting ligero ocasional y pesca de orilla',
    '- Perfecto para quien empieza o busca un carrete de repuesto barato',
    '- Lo mejor: Precio imbatible, marca Daiwa, bobina amplia',
    '',
    'La opción si tu presupuesto es mínimo y necesitas un carrete que lance y recojas sin dramas.',
    '',
    '---',
    '',
    '## Cómo elegir tu carrete de surfcasting',
    '',
    '### 1. Tamaño: de 5000 hacia arriba',
    'El surfcasting exige bobinas grandes porque necesitas mucha capacidad de trenzado para lances largos y porque la recuperación por vuelta de manivela es mayor. Un 4000 puede valer para surfcasting ligero, pero el estándar para cañas de 4.20m son tamaños de 6000 a 14000. A más tamaño, más capacidad y más rápido recuperas, aunque también más peso.',
    '',
    '### 2. Relación de recuperación',
    'Busca relaciones que recuperen entre 85 y 100 centímetros por vuelta de manivela. Con un carrete de recuperación corta, recuperar 150 metros de línea en una captura es un suplicio. Los carretes de surfcasting suelen montar relaciones de 4.0:1 a 5.0:1.',
    '',
    '### 3. Freno: la clave en el lance largo',
    'En surfcasting no necesitas un freno enorme (con 10-12kg vas sobrado), pero sí progresivo y suave. Un freno seco corta el aparejo en el clavado. Los frenos de carbono (como el HT-100 de PENN o el ATD de Daiwa) son los más suaves y fiables.',
    '',
    '### 4. Resistencia a la sal',
    'Es el factor que más diferencia a los carretes de surfcasting de los de agua dulce. Busca rodamientos de acero inoxidable y, si puedes, protección del cuerpo contra el agua (CoreProtect en Shimano, sellados HT-100 en PENN). Un carrete de agua dulce dura meses en la playa; uno de mar, años.',
    '',
    '### 5. El peso importa, pero no lo es todo',
    'Un carrete ligero (como el Ninja LT de 335g) reduce la fatiga en jornadas de 6-8 horas lanzando. Pero un carrete demasiado ligero puede desequilibrar cañas de acción pesada. Busca el equilibrio con la caña que ya tienes.',
    '',
    '---',
    '',
    '## Preguntas frecuentes',
    '',
    '### ¿Qué tamaño de carrete necesito para surfcasting?',
    'Con una caña de 4.20m, un tamaño 6000 es el mínimo recomendable para surfcasting serio. Si lanzas plomos de 120-150 gramos a mucha distancia, sube a 8000-10000. Los tamaños 14000 como el Ultegra son para pesca de fondo potente y cañas de 4.50m o más.',
    '',
    '### ¿Puedo usar un carrete de spinning normal para surfcasting?',
    'Puedes, pero no es lo ideal. Los carretes de surfcasting tienen bobinas más largas y específicas para el lance, recuperación más rápida y mejores protecciones contra la sal. Con un spinning normal de 4000 harás surfcasting ligero con cañas cortas, pero te perderás la mitad de la distancia y arriesgarás el carrete en el mar.',
    '',
    '### ¿Qué trenzado le pongo a mi carrete de surfcasting?',
    'Para surfcasting se usa trenzado fino y de alta resistencia: 0.16-0.20mm es lo habitual en la mayoría de carretes de la lista. El trenzado fino sale mejor en el lance y aguanta bien en la roca. Compleméntalo con un bajo de línea de fluorocarbono de 0.40-0.60mm contra los raspones del fondo.',
    '',
    '### ¿Cuánto cuesta un buen carrete de surfcasting?',
    'Puedes empezar con 30-45€ (Joinus, MX2) y tener un equipo funcional. Con 50-70€ (Ninja LT, Surfblaster) consigues un carrete que aguanta temporadas. A partir de 150€ (Ultegra) entras en carretes que duran décadas y que se notan sobre todo en el lance y en la suavidad del freno.',
    '',
    '### ¿Cada cuánto tengo que mantener el carrete si pesco en el mar?',
    'Acláralo con agua dulce después de cada jornada de mar, aunque sea con manguera. Engrasa los rodamientos y el mecanismo una vez por temporada (o cada 4-5 salidas si pescas mucho). Con ese mínimo, un carrete de mar bien elegido de esta lista te dura años.',
    '',
    '---',
    '',
    '## Veredicto final',
    '',
    'El **Shimano Ultegra 14000 XSE** es el mejor carrete de surfcasting que puedes comprar si el presupuesto no es un problema: protección CoreProtect, engranajes Hagane y una bobina pensada para el lance largo. Es un carrete de los que duran décadas.',
    '',
    'Si quieres resistencia salada sin pagar 150€, el **PENN Surfblaster III** es la elección más sensata. Y para el 90% de los pescadores que buscan el mejor equilibrio entre precio y prestaciones, el **Daiwa Ninja LT 6000** es, sin discusión, el mejor carrete de surfcasting calidad-precio de 2026.',
    '',
    'Empieza por donde te sientas cómodo: ninguno de los seis te va a defraudar, pero elige según la frecuencia con la que pesques y cuánto estés dispuesto a cuidarlo. El mejor carrete es el que se adapta a tu bolsillo y a tu estilo de pesca.',
  ].join('\n')

  const productsData = JSON.stringify([
    {
      title: 'Shimano Ultegra 14000 XSE',
      rating: 4.8,
      image: 'https://m.media-amazon.com/images/I/61FH-Lc+F2L._AC_SX679_.jpg',
      scores: { 'Resistencia salada': 96, Suavidad: 92, 'Calidad/Precio': 62, Potencia: 95, 'Apto surfcasting': 98 },
      slug: 'shimano-ultegra-14000-xse---carrete-surfcasting',
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B09Z11GYT7', price: '188,70€' }],
      badge: 'Mejor en general',
      badgeColor: '#00D4FF',
    },
    {
      title: 'PENN Surfblaster III',
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/718wS6uEdQS._AC_SL1500_.jpg',
      scores: { 'Resistencia salada': 94, Suavidad: 84, 'Calidad/Precio': 78, Potencia: 88, 'Apto surfcasting': 92 },
      slug: 'penn-surfblaster-iii-carrete-de-pesca-de-lanzamiento-largo-para-surf-playa-y-pes',
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B08MPM7SC9', price: '142,00€' }],
      badge: 'Mejor resistencia salada',
      badgeColor: '#6366F1',
    },
    {
      title: 'Daiwa Ninja 23 LT 6000',
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/61+Evme+0DL._AC_SX679_.jpg',
      scores: { 'Resistencia salada': 78, Suavidad: 88, 'Calidad/Precio': 96, Potencia: 82, 'Apto surfcasting': 85 },
      slug: 'daiwa-ninja-23-lt-6000---carrete-pesca-mar',
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0CH18X222', price: '52,65€' }],
      badge: 'Mejor calidad-precio',
      badgeColor: '#22C55E',
    },
    {
      title: 'Mitchell MX2 (agua salada)',
      rating: 4.4,
      image: 'https://m.media-amazon.com/images/I/716e1cd7CzL._AC_SL1500_.jpg',
      scores: { 'Resistencia salada': 82, Suavidad: 72, 'Calidad/Precio': 90, Potencia: 74, 'Apto surfcasting': 76 },
      slug: 'mitchell-carrete-giratorio-de-agua-salada-mx2-el-carrete-de-pesca-de-mar-ideal-p',
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0CDLY1JP7', price: '44,49€' }],
      badge: 'Recomendado <50€',
      badgeColor: '#F59E0B',
    },
    {
      title: 'Shimano Sienna FG 4000',
      rating: 4.5,
      image: 'https://m.media-amazon.com/images/I/61lpfbpSZQL._AC_SX679_.jpg',
      scores: { 'Resistencia salada': 62, Suavidad: 70, 'Calidad/Precio': 95, Potencia: 70, 'Apto surfcasting': 68 },
      slug: 'shimano-sienna-fg-4000---carrete-spinning',
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0873PQW96', price: '38,99€' }],
      badge: 'El más fiable para empezar',
      badgeColor: '#6366F1',
    },
    {
      title: 'Daiwa Joinus 5000',
      rating: 4.2,
      image: 'https://m.media-amazon.com/images/I/61petIvJSaL._AC_SX679_.jpg',
      scores: { 'Resistencia salada': 60, Suavidad: 62, 'Calidad/Precio': 92, Potencia: 68, 'Apto surfcasting': 64 },
      slug: 'daiwa-joinus-5000---carrete-pesca-marina',
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B01BG9I492', price: '30,20€' }],
      badge: 'Económico',
      badgeColor: '#EF4444',
    },
  ])

  const fullContent = content + `\n\n<!-- PRODUCTS_DATA: ${productsData} -->`

  const id = `post_surfcasting_carretes_${Date.now()}`

  const existing = await db.execute({ sql: 'SELECT id FROM posts WHERE slug = ?', args: [slug] })
  if (existing.rows.length > 0) {
    await db.execute({
      sql: `UPDATE posts SET title = ?, excerpt = ?, content = ?, category = ?, tags = ?, relatedAsins = ?, metaTitle = ?, metaDescription = ?, focusKeyword = ?, updatedAt = ? WHERE slug = ?`,
      args: [
        'Los mejores carretes de surfcasting de 2026: guía y comparativa',
        '¿Buscas un carrete de surfcasting? Comparamos los mejores modelos de 2026 con precio real: Shimano Ultegra 14000 XSE, PENN Surfblaster III, Daiwa Ninja LT 6000, Mitchell MX2, Shimano Sienna FG 4000 y Daiwa Joinus 5000. Guía de compra con pros y contras.',
        fullContent,
        'Carretes',
        JSON.stringify(['carretes surfcasting', 'surfcasting', 'carretes pesca', 'guias compra']),
        JSON.stringify(['B09Z11GYT7', 'B08MPM7SC9', 'B0CH18X222', 'B0CDLY1JP7', 'B0873PQW96', 'B01BG9I492']),
        'Los mejores carretes de surfcasting de 2026 | PesCatch Blog',
        'Comparativa de carretes de surfcasting con precios reales: Ultegra 14000, PENN Surfblaster III, Ninja LT 6000, MX2, Sienna y Joinus. Cómo elegir tamaño, freno y resistencia salada.',
        'mejores carretes de surfcasting 2026',
        now,
        slug,
      ],
    })
    console.log(`✅ Post actualizado: ${slug}`)
    return
  }

  await db.execute({
    sql: `INSERT INTO posts (id, title, slug, excerpt, content, featuredImage, author, category, tags, relatedAsins, status, metaTitle, metaDescription, canonicalUrl, focusKeyword, publishedAt, createdAt, updatedAt)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      id,
      'Los mejores carretes de surfcasting de 2026: guía y comparativa',
      slug,
      '¿Buscas un carrete de surfcasting? Comparamos los mejores modelos de 2026 con precio real: Shimano Ultegra 14000 XSE, PENN Surfblaster III, Daiwa Ninja LT 6000, Mitchell MX2, Shimano Sienna FG 4000 y Daiwa Joinus 5000. Guía de compra con pros y contras.',
      fullContent,
      '',
      'PesCatch',
      'Carretes',
      JSON.stringify(['carretes surfcasting', 'surfcasting', 'carretes pesca', 'guias compra']),
      JSON.stringify(['B09Z11GYT7', 'B08MPM7SC9', 'B0CH18X222', 'B0CDLY1JP7', 'B0873PQW96', 'B01BG9I492']),
      'published',
      'Los mejores carretes de surfcasting de 2026 | PesCatch Blog',
      'Comparativa de carretes de surfcasting con precios reales: Ultegra 14000, PENN Surfblaster III, Ninja LT 6000, MX2, Sienna y Joinus. Cómo elegir tamaño, freno y resistencia salada.',
      '',
      'mejores carretes de surfcasting 2026',
      now,
      now,
      now,
    ],
  })

  console.log(`✅ Blog post seeded: ${slug}`)
}

seedBlogPost().catch(console.error)
