import { getDb, initSchema } from '../src/lib/db'

async function seedBlogPost() {
  const db = getDb()
  await initSchema()

  const slug = 'mejores-gafas-sol-polarizadas-pescar-2026'
  const now = new Date().toISOString()

  const content = [
    'Si pescas al sol, tarde o temprano acabas con los ojos rojos, llorando, y viendo los reflejos del agua hasta en la sopa. Las gafas de sol polarizadas no son un capricho: cortan el brillo de la superficie, te dejan ver las picadas debajo del agua y protegen la vista de los rayos UV que rebotan en la mar. Y con los descuentos que hay ahora mismo en Amazon, no hay excusa para no llevar unas.',
    '',
    'He mirado los chollos que tenemos publicados en PesCatch y he seleccionado las 6 mejores gafas polarizadas para pescar por precio. Todas con descuento real ahora mismo, no de esos precios inflados para la foto.',
    '',
    '## Para los que tienen prisa',
    '',
    'Las **HAWKERS Carbon One** son el chollo del año con un -51% y un diseño que sirve tanto para pescar como para el día a día. Las **Polaroid PLD 7005/S** son la calidad-precio con una marca histórica de polarizados. Las **Lamicall 22g** son las más cómodas para jornadas largas. Y si vas justo de presupuesto, las **Hifot** por 11€ cumplen de sobra.',
    '',
    '---',
    '',
    '## 1. HAWKERS Carbon One — El chollo del año (-51%)',
    '',
    '<!--PRODUCT_IMG:1-->',
    '',
    'Las **HAWKERS Carbon One** son el mejor chollo de gafas que hemos visto este año: pasan de 44,99€ a 22€. Son ligeras, con montura de carbono que aguanta la brisa marina y el trato brusco del cofre, y cristal polarizado con protección UV400 que corta el reflejo del agua de forma brutal.',
    '',
    'El diseño envolvente hace que te protejan también los lados, algo que se agradece cuando el sol pega de través en el espigón. Y la funda rígida que traen las hace fáciles de guardar en la mochila sin que se rayen las lentes.',
    '',
    '- **Precio:** 22€ (antes 44,99€) | **Polarizado:** Sí | **UV400:** Sí',
    '- Montura de carbono ligera y resistente al agua salada',
    '- Cristal polarizado con filtro UV400',
    '- Ideal para pescar de día en mar y río',
    '- Lo mejor: Descuento brutal, ligereza, diseño envolvente',
    '',
    'Por 22€ es casi imposible encontrar algo mejor. Compra para tener unas de repuesto en el coche sin pensártelo dos veces.',
    '',
    '---',
    '',
    '## 2. Polaroid PLD 7005/S — La calidad-precio de una marca histórica (-47%)',
    '',
    '<!--PRODUCT_IMG:2-->',
    '',
    'Polaroid inventó el cristal polarizado, así que saben de lo que hablan. Las **PLD 7005/S** bajan de 55€ a 29€ y montan la lente polarizada más cuidada de esta lista, con un filtro verde que levanta el contraste en agua clara y mejora la visión en profundidad.',
    '',
    'La montura es de acetato con flexibilidad en las patillas, cómoda para caras anchas y estables aunque sudes. El ajuste es de esos que notas que están bien hechos desde el primer día, sin bailar ni apretar de más.',
    '',
    '- **Precio:** 29€ (antes 55€) | **Polarizado:** Sí | **UV400:** Sí',
    '- Lente Polaroid genuina con filtro verde de alto contraste',
    '- Montura de acetato con patillas flexibles',
    '- Ideal para pesca en agua clara y jornadas largas',
    '- Lo mejor: Óptica de marca, acabado premium por el precio',
    '',
    'Si valoras la calidad óptica por encima del diseño, estas son las tuyas.',
    '',
    '---',
    '',
    '## 3. Lamicall Polarizadas 22g — Las más cómodas para todo el día (-13%)',
    '',
    '<!--PRODUCT_IMG:3-->',
    '',
    'Pesar solo **22 gramos** se nota cuando llevas las gafas puestas seis horas seguidas. Las **Lamicall** están pensadas para deporte: montura TR90 flexible que no se rompe, diseño envolvente que tapa los lados, y almohadilla nasal ajustable para que no te resbalen con el sudor ni con las salpicaduras.',
    '',
    'Son las típicas gafas que te pones para pescar y te olvidas de que las llevas. El polarizado UV400 está a la altura y el precio de 26€ con descuento es correcto para lo que ofrecen.',
    '',
    '- **Precio:** 26€ (antes 29,99€) | **Polarizado:** Sí | **UV400:** Sí',
    '- Solo 22g, montura TR90 ultraligera y flexible',
    '- Almohadilla nasal ajustable y diseño envolvente',
    '- Ideal para spinning, kayak y jornadas de sol a sol',
    '- Lo mejor: Peso pluma, sujeción, resistencia a golpes',
    '',
    'La opción más sensata para el que pesca muchas horas y no quiere notar las gafas en la cara.',
    '',
    '---',
    '',
    '## 4. GQUEEN Polarizadas de Madera — El toque distinto (-16%)',
    '',
    '<!--PRODUCT_IMG:4-->',
    '',
    'Las **GQUEEN** son las más llamativas de la lista: montura de madera de estilo clásico-rectangular que queda bien en la orilla, en el barco y luego en la terraza. No son las más deportivas, pero sí las que mejor combinan con ropa casual de pesca.',
    '',
    'El cristal polarizado con protección UV400 cumple en el agua, y la construcción en madera natural es ligera y sorprendentemente resistente. Por 16€ con descuento, son perfectas para tener unas que no te duela rayar.',
    '',
    '- **Precio:** 16€ (antes 18,98€) | **Polarizado:** Sí | **UV400:** Sí',
    '- Montura de madera natural ligera y resistente',
    '- Estilo clásico-rectangular que combina con todo',
    '- Ideal para pesca desde orilla y uso diario',
    '- Lo mejor: Estética única, precio imbatible',
    '',
    'Para el que quiere gafas de pesca que además queden bien fuera del agua.',
    '',
    '---',
    '',
    '## 5. Cressi Rio Sunglasses — La deportiva de buceo (-16%)',
    '',
    '<!--PRODUCT_IMG:5-->',
    '',
    'Cressi es marca de buceo, así que entiende de ópticas que tienen que funcionar en el agua. Las **Rio** son unas deportivas envolventes con lente polarizada, protección UV y un ajuste ceñido que aguanta el viento de la playa y la sal del mar sin quejarse.',
    '',
    'Por 21€ (antes 24,99€) tienes una gafa construida para entornos acuáticos, con un campo de visión amplio y buena sujeción lateral. Son ideales como gafas técnicas para pescar en barco o en roca, donde la protección es prioridad.',
    '',
    '- **Precio:** 21€ (antes 24,99€) | **Polarizado:** Sí | **UV400:** Sí',
    '- Marca con ADN de buceo, óptica pensada para el agua',
    '- Diseño envolvente con buena sujeción lateral',
    '- Ideal para barco, roca y pesca deportiva',
    '- Lo mejor: Robustez, campo de visión amplio',
    '',
    'La deportiva de verdad, de una casa que sabe lo que es mirar al agua durante horas.',
    '',
    '---',
    '',
    '## 6. Hifot Polarizadas UV400 — La económica que cumple (-21%)',
    '',
    '<!--PRODUCT_IMG:6-->',
    '',
    'Por solo **11€** (antes 13,99€) las **Hifot** son la opción para el que quiere gastarse lo justo. Tienen lente polarizada UV400, montura deportiva ultraligera que cubre los laterales, y sirven para pesca y para ciclismo o running sin problemas.',
    '',
    'No son las de mayor calidad de la lista, eso está claro, pero por ese precio son ideales para tener un par de repuesto en el coche, en la caja de pesca o para empezar a pescar sin gastar. La relación prestaciones-precio es honesta.',
    '',
    '- **Precio:** 11€ (antes 13,99€) | **Polarizado:** Sí | **UV400:** Sí',
    '- Montura deportiva ultraligera y envolvente',
    '- Sirven para pesca, ciclismo y running',
    '- Ideal como repuesto o primera gafa polarizada',
    '- Lo mejor: Precio mínimo, funcionalidad completa',
    '',
    'Si solo quieres unas gafas que hagan bien su trabajo sin rascarte el bolsillo, esta es tu opción.',
    '',
    '---',
    '',
    '## Conclusión: ¿cuál me compro?',
    '',
    '- **Presupuesto flexible / mejor chollo:** HAWKERS Carbon One a 22€ con -51%. No hay discusión.',
    '- **Máxima calidad óptica:** Polaroid PLD 7005/S a 29€. La lente es la mejor de la lista.',
    '- **Jornadas largas y deporte:** Lamicall 22g a 26€. Ni las notas puestas.',
    '- **Estilo + pesca:** GQUEEN de madera a 16€.',
    '- **Barco y roca:** Cressi Rio a 21€.',
    '- **Presupuesto mínimo:** Hifot a 11€.',
    '',
    'Recuerda: los precios y descuentos son los que tenemos capturados ahora mismo en PesCatch. Si alguno se agota o sube, la propia web lo refleja. Las polarizadas son de las pocas cosas de pesca que no deberías comprar barato y mal, pero con estos chollos tampoco hace falta pagar de más.',
    '',
    '---',
    '',
    '## Preguntas frecuentes',
    '',
    '### ¿Por qué necesito gafas polarizadas para pescar?',
    '',
    'El cristal polarizado bloquea la luz reflejada horizontal en la superficie del agua. Resultado: ves a través de la superficie, localizas bancos de peces y detectas picadas que a simple vista se pierden en el brillo. Además evitas el cansancio y el daño ocular del reflejo intenso.',
    '',
    '### ¿Qué significa UV400?',
    '',
    'Que la lente filtra el 99-100% de los rayos UVA y UVB. En la pesca es imprescindible porque el agua y la arena reflejan la radiación y te llega también por debajo y por los lados, no solo de frente.',
    '',
    '### ¿Mejor lente de color verde, gris o ámbar?',
    '',
    'Depende del agua. La lente verde (como la de la Polaroid) levanta el contraste en aguas claras y es la favorita para pesca de depredadores. El gris distorsiona menos los colores y sirve para todo. El ámbar o marrón va bien en condiciones de poca luz o agua turbia. Cualquiera de las que te hemos dejado cumple en pesca de día.',
    '',
    '### ¿Puedo usar gafas de ciclismo para pescar?',
    '',
    'Sí, sin problema. Las deportivas envolventes (Lamicall, Hifot) protegen mejor los lados del viento y la sal, y suelen ser más resistentes que unas gafas de calle. Por eso las hemos incluido en la comparativa.',
    '',
    '### ¿Estos precios son de verdad o inflados?',
    '',
    'Son los precios reales que tenemos capturados y comparados entre tiendas en PesCatch. Los descuentos son sobre el precio original que marca la propia tienda. Cuando se acaba el stock o sube el precio, la web lo actualiza.',
    '',
  ].join('\n')

  const productsData = JSON.stringify([
    {
      title: 'HAWKERS Carbon One Gafas de Sol',
      rating: 4.4,
      image: 'https://m.media-amazon.com/images/I/41IARWC-UkL._AC_SL1500_.jpg',
      scores: { Polarización: 85, 'Protección UV': 90, Comodidad: 80, Ligereza: 85, 'Calidad/Precio': 98 },
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B08D9QWZB5', price: '22€' }],
      slug: 'hawkers-gafas-de-sol-carbon-one-para-hombre-y-mujer',
    },
    {
      title: 'Polaroid PLD 7005/S Flexi Temples',
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/61CIEnUMsaL._AC_SL1500_.jpg',
      scores: { Polarización: 95, 'Protección UV': 90, Comodidad: 82, Ligereza: 75, 'Calidad/Precio': 88 },
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B01BKO9VJ0', price: '29€' }],
      slug: 'polaroid-pld-7005s-black-flexi-templesgreen-6317123-men-sunglasses',
    },
    {
      title: 'Lamicall Polarizadas 22g UV400',
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/51aem7r-ydL._AC_SL1500_.jpg',
      scores: { Polarización: 82, 'Protección UV': 90, Comodidad: 95, Ligereza: 98, 'Calidad/Precio': 82 },
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0GFWSN381', price: '26€' }],
      slug: 'lamicall-polarizadas-gafas-de-sol-ciclismo---22g-diseo-envolvente-uv400-protecci',
    },
    {
      title: 'GQUEEN Polarizadas de Madera UV400',
      rating: 4.5,
      image: 'https://m.media-amazon.com/images/I/51RhFZCOQiL._AC_SL1500_.jpg',
      scores: { Polarización: 80, 'Protección UV': 90, Comodidad: 78, Ligereza: 85, 'Calidad/Precio': 90 },
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B07WS391LQ', price: '16€' }],
      slug: 'gqueen-gafas-de-sol-polarizadas-rectangulares-clsicas-de-madera-para-hombres-y-m',
    },
    {
      title: 'Cressi Rio Sunglasses Polarizadas',
      rating: 3.8,
      image: 'https://m.media-amazon.com/images/I/61F2q7UszZL._AC_SL1500_.jpg',
      scores: { Polarización: 80, 'Protección UV': 88, Comodidad: 75, Ligereza: 72, 'Calidad/Precio': 85 },
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B01MT09FSJ', price: '21€' }],
      slug: 'cressi-rio-sunglasses---gafas-de-sol-deportivo-polarizados-unisex-adultos',
    },
    {
      title: 'Hifot Polarizadas Deportivas UV400',
      rating: 3.7,
      image: 'https://m.media-amazon.com/images/I/61TxmNhrHIL._AC_SL1500_.jpg',
      scores: { Polarización: 75, 'Protección UV': 85, Comodidad: 72, Ligereza: 85, 'Calidad/Precio': 95 },
      stores: [{ name: 'Amazon', url: 'https://www.amazon.es/dp/B0F86PK92Y', price: '11€' }],
      slug: 'hifot-gafas-de-sol-polarizadas-deportivas-hombre-mujer-proteccin-uv400-gafas-cic',
    },
  ])

  const fullContent = content + `\n\n<!-- PRODUCTS_DATA: ${productsData} -->`

  const existing = await db.execute({
    sql: 'SELECT id FROM posts WHERE slug = ?',
    args: [slug],
  })

  const title = 'Las 6 mejores gafas de sol polarizadas para pescar en 2026'
  const excerpt = 'Gafas de sol polarizadas para pescar al mejor precio. Comparamos HAWKERS Carbon One a 22€, Polaroid PLD 7005/S, Lamicall, GQUEEN, Cressi y Hifot. Guía con descuentos reales, pros, contras y FAQ.'
  const featuredImage = 'https://m.media-amazon.com/images/I/41IARWC-UkL._AC_SL1500_.jpg'
  const tags = JSON.stringify(['gafas polarizadas pesca', 'gafas de sol pesca', 'gafas pesca', 'mejores gafas polarizadas', 'pesca verano'])
  const relatedAsins = JSON.stringify(['B08D9QWZB5', 'B01BKO9VJ0', 'B0GFWSN381', 'B07WS391LQ', 'B01MT09FSJ', 'B0F86PK92Y'])

  if (existing.rows.length > 0) {
    const id = existing.rows[0].id as string
    await db.execute({
      sql: `UPDATE posts SET title = ?, excerpt = ?, content = ?, featuredImage = ?,
        author = ?, category = ?, tags = ?, relatedAsins = ?, updatedAt = ?
        WHERE id = ?`,
      args: [title, excerpt, fullContent, featuredImage, 'PesCatch', 'Accesorios', tags, relatedAsins, now, id],
    })
    console.log(`✅ Blog post updated: ${slug}`)
  } else {
    await db.execute({
      sql: `INSERT INTO posts (id, title, slug, excerpt, content, featuredImage, author, category, tags, relatedAsins, hidden, publishedAt, createdAt, updatedAt)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        `post_${Date.now()}`,
        title,
        slug,
        excerpt,
        fullContent,
        featuredImage,
        'PesCatch',
        'Accesorios',
        tags,
        relatedAsins,
        0, now, now, now,
      ],
    })
    console.log(`✅ Blog post created: ${slug}`)
  }
}

seedBlogPost().catch(console.error)
