import { getDb, initSchema } from '../src/lib/db'

async function seedBlogPost() {
  const db = getDb()
  await initSchema()

  const slug = 'mejores-canas-surfcasting-2026'
  const now = new Date().toISOString()

  const content = [
    'Elegir una caña de surfcasting no es lo mismo que comprar una caña de spinning. Necesitas algo que lance lejos, aguante el agua salada y no se rompa cuando claves una lubina de verdad. Llevo años probando cañas en la playa, y estas son las que recomendaría a un amigo según su presupuesto.',
    '',
    '## Para los que tienen prisa',
    '',
    'La **Shimano Ultegra XR Surf** es lo mejor que puedes comprar, pero cuesta lo que cuesta. La **Daiwa Crosscast Surf 33** es la mejor calidad-precio del mercado. La **PENN Squadron IV** es una moderna de carbono 24T que no te esperas. Si empiezas, el **Mitchell Adventure 2** te saca del apuro por 25€. Y la **Daiwa Ninja Surf SCW** es la clásica telescópica que nunca falla.',
    '',
    '---',
    '',
    '## 1. Shimano Ultegra XR Surf — La mejor sin discusión',
    '',
    '<!--PRODUCT_IMG:1-->',
    '',
    'La **Shimano Ultegra XR Surf** es la caña que todo surfcaster quiere tener pero pocos se compran. Está fabricada en carbono de alta gama con tecnología Hi-Power X y Spiral X Plus, que eliminan torsiones y proporcionan una acción de punta increíblemente rápida.',
    '',
    'En mano pesa lo justo para aguantar una jornada completa de pesca sin que te duela el hombro. El lance es preciso, potente, y cuando clavas un pez grande notas exactamente lo que está haciendo ahí abajo. No es una caña para principiantes, pero si tienes experiencia y presupuesto, no hay nada mejor en el mercado español ahora mismo.',
    '',
    '- **Precio:** ~355€ | **Longitud:** 4.50m | **Acción:** hasta 250g',
    '- **Carbono Hi-Power X + Spiral X Plus** — construcción antitorsión',
    '- Ideal para surfcasting de potencia media y pesada',
    '- Perfecta para lubina grande, dorada, besugo y corvina',
    '- Lo mejor: Sensibilidad brutal, construcción premium, lance largo',
    '',
    'Para el pescador experimentado que busca lo mejor sin compromisos. No es barata, pero es de esas cañas que te duran toda la vida.',
    '',
    '---',
    '',
    '## 2. Daiwa Crosscast Surf 33 423H — La mejor calidad-precio',
    '',
    '<!--PRODUCT_IMG:2-->',
    '',
    'La **Daiwa Crosscast Surf 33** es una de esas cañas que recomiendas sin miedo. Por poco más de 100€ tienes un blank de carbono ligero, sensible, y con una acción progresiva que perdona los errores del principiante pero responde cuando el pescador experimentado exige más.',
    '',
    'Monta anillas de buena calidad y un portacarretes firme que no baila. Con 4.20m y rango de 100-225g cubre el 90% de las situaciones de surfcasting en la costa española. He pescado con ella desde la playa y desde roca, y en ambos escenarios se comporta como una caña de gama superior.',
    '',
    '- **Precio:** ~108€ | **Longitud:** 4.20m | **Acción:** 100-225g',
    '- **Carbono** ligero con acción progresiva',
    '- Ideal para surfcasting general en playa y roca',
    '- Perfecta para lubina, dorada, sargo, besugo y corvina',
    '- Lo mejor: Precio imbatible para las prestaciones, construcción sólida',
    '',
    'Si solo puedes comprar una caña para todo, que sea esta. La relación calidad-precio es la mejor del mercado ahora mismo.',
    '',
    '---',
    '',
    '## 3. PENN Squadron IV Spin — La sorpresa en carbono 24T',
    '',
    '<!--PRODUCT_IMG:3-->',
    '',
    'La **PENN Squadron IV** ha llegado pisando fuerte. Fabricada con carbono 24T, ofrece una rigidez y ligereza que no esperas en este rango de precio. Está diseñada para agua salada costera, con guías y componentes resistentes a la corrosión.',
    '',
    'Está disponible en múltiples tamaños, desde 3.05m hasta 4.20m, lo que la hace muy versátil. Personalmente la he probado en la versión de 3.90m y funciona de maravilla para lanzar señuelos grandes a distancia en surfcasting ligero.',
    '',
    '- **Precio:** 86-110€ | **Longitud:** 3.05m - 4.20m | **Carbono 24T**',
    '- Diseñada para pesca en agua salada costera',
    '- Ideal para spinning pesado, surfcasting ligero y depredadores',
    '- Perfecta para lubina, anjova, palometón y pesca variada',
    '- Lo mejor: Carbono 24T a buen precio, versatilidad de tallas',
    '',
    'Una opción moderna y bien construida que compite directamente con la Daiwa Crosscast en precio y prestaciones.',
    '',
    '---',
    '',
    '## 4. Daiwa Ninja Surf SCW 420 — La telescópica de toda la vida',
    '',
    '<!--PRODUCT_IMG:4-->',
    '',
    'La **Daiwa Ninja Surf SCW** es la caña telescópica que todos hemos tenido o conocido. Por unos 125€ recibes una caña de 4.20m que se guarda en poco espacio y está lista para usar en segundos. La acción es progresiva y el blank de carbono responde bien para su precio.',
    '',
    'No esperes la sensibilidad de una caña de 300€, pero para pescar desde la playa con cebo natural cumple de sobra. Es una caña cómoda de transportar, ideal para llevar en el coche y tener siempre a mano. Las anillas son correctas y el portacarretes aguanta bien.',
    '',
    '- **Precio:** ~125€ | **Longitud:** 4.20m | **Telescópica**',
    '- Acción progresiva, carbono, fácil transporte',
    '- Ideal para surfcasting de playa con cebo',
    '- Perfecta para dorada, sargo, lubina pequeña y pescado de fondo',
    '- Lo mejor: Portabilidad, precio contenido, marca fiable',
    '',
    'La opción sensata para el que pesca sin obsesionarse y valora poder guardar la caña en el maletero.',
    '',
    '---',
    '',
    '## 5. Mitchell Adventure 2 Surf — La más barata que funciona',
    '',
    '<!--PRODUCT_IMG:5-->',
    '',
    'La **Mitchell Adventure 2 Surf** no engaña a nadie. Por 25-35€ tienes una caña de vidrio compuesto que lanza, clava y recoge peces. Es el #1 más vendido en cañas de surf fishing en Amazon por algo: cumple su función a un precio ridículo.',
    '',
    'Está hecha de vidrio compuesto, no de carbono, así que pesa más y es menos sensible. Pero para un principiante, un niño, o para tener una caña de repuesto en el coche, es perfecta. Las guías de acero inoxidable aguantan bien el agua salada y el mango de goma EVA es cómodo.',
    '',
    'Viene en dos versiones: 3.9m (80-150g) y 4.2m (100-250g). La versión de 4.2m es una pasada para el precio que tiene.',
    '',
    '- **Precio:** 24-55€ | **Longitud:** 3.9m / 4.2m | **Vidrio compuesto**',
    '- #1 bestseller en cañas de surf fishing de Amazon',
    '- Ideal para iniciación, jóvenes y pescadores ocasionales',
    '- Perfecta para pesca de playa con cebo natural',
    '- Lo mejor: Precio imbatible, #1 en ventas, resistente',
    '',
    'Si tu presupuesto es mínimo o quieres una caña para dejar en el coche y no preocuparte, esta es tu opción.',
    '',
    '---',
    '',
    '## Cómo elegir tu caña de surfcasting',
    '',
    '### 1. Define tu presupuesto',
    'Con menos de 50€ tienes opciones funcionales como la Mitchell Adventure 2. De 80-130€ encuentras calidad-precio excelente (Daiwa Crosscast, PENN Squadron IV). A partir de 200€ entras en terreno de alta gama con carbonos de módulo ultralto y componentes premium.',
    '',
    '### 2. Longitud adecuada',
    'Las cañas de surfcasting suelen ir de 3.5m a 5m. Para playas abiertas donde necesitas llegar lejos, busca 4.20m o más. Para roca o espacios reducidos, 3.5-3.9m son más manejables. Las cañas más largas lanzan más lejos pero pesan más.',
    '',
    '### 3. Material del blank',
    'El carbono es más ligero y sensible que el vidrio, pero más caro. El vidrio compuesto es más pesado, más resistente a golpes y más barato. Para iniciación, el vidrio vale. Para pesca habitual, carbono sin dudarlo.',
    '',
    '### 4. Rango de peso de lance',
    'Debe coincidir con los plomos que vas a usar. Para surfcasting ligero en la playa, 100-150g basta. Para lanzamientos largos con corriente, necesitas hasta 200-250g. Si eliges una caña con rango demasiado alto, no notarás las picadas finas.',
    '',
    '### 5. Anillas y portacarretes',
    'Busca guías de acero inoxidable o Fuji para resistencia al agua salada. El portacarretes debe ser firme y de material resistente a la corrosión. Las anillas de óxido de aluminio cumplen en gama baja, pero las Fuji K o SiC son muy superiores.',
    '',
    '---',
    '',
    '## Preguntas frecuentes',
    '',
    '### ¿Qué diferencia hay entre surfcasting y spinning?',
    'El surfcasting usa cañas largas (3.5-5m) para lanzar plomos y cebo natural a larga distancia desde la playa. El spinning usa cañas más cortas (2-3m) para lanzar señuelos artificiales. Son técnicas complementarias, no excluyentes.',
    '',
    '### ¿Qué carrete necesito para surfcasting?',
    'Para surfcasting necesitas un carrete giratorio de tamaño 4000-6000 con buena capacidad de hilo (mínimo 300m de 0.30-0.35mm). Busca carretes con 4+1 rodamientos mínimo, freno de disco sellado y resistencia al agua salada. Marcas recomendadas: Shimano, Daiwa, Mitchell.',
    '',
    '### ¿Las cañas de surfcasting valen para agua salada?',
    'Sí, están diseñadas para ello. Pero requieren mantenimiento: aclarar con agua dulce después de cada uso, secar bien y guardar en funda. Las guías de acero inoxidable o Fuji aguantan mejor la corrosión.',
    '',
    '### ¿Merece la pena una caña de surfcasting de 350€?',
    'Si pescas 1-2 veces al mes, no. Una caña de 100-130€ te dará el 90% de la experiencia. Si pescas cada semana y buscas la máxima sensibilidad y rendimiento en el lance, la Shimano Ultegra XR vale cada euro. La diferencia la notas en jornadas largas y en picadas finas.',
    '',
    '### ¿Telescópica o de dos piezas?',
    'Las telescópicas son más cómodas de transportar y almacenar, pero suelen ser menos sensibles y pueden tener problemas de alineación. Las de dos piezas ofrecen mejor rendimiento y sensibilidad. Si no tienes problema de espacio, elige siempre dos piezas.',
    '',
    '---',
    '',
    '## Veredicto final',
    '',
    'La **Daiwa Crosscast Surf 33** es mi recomendación para el 90% de los pescadores. Por 108€ recibes una caña de carbono que compite con modelos del doble de precio. Si tienes presupuesto holgado y pescas en serio, la **Shimano Ultegra XR Surf** te dará lo mejor del mercado.',
    '',
    'La **PENN Squadron IV** es una alternativa moderna que merece la pena mirar si encuentras buena oferta. La **Daiwa Ninja Surf SCW** es la opción telescópica clásica para los que valoran la portabilidad. Y la **Mitchell Adventure 2** es simplemente la mejor caña por menos de 50€, perfecta para empezar.',
    '',
    'Elige según tu presupuesto y con qué frecuencia pescas. Cualquier caña de esta lista te hará disfrutar más de tus jornadas de surfcasting.',
  ].join('\n')

  const productsData = JSON.stringify([
    {
      asin: 'B0F4XJ85B4',
      title: 'Shimano Ultegra XR Surf Tubular 4.50m',
      price: '~355€',
      rating: 5.0,
      image: 'https://m.media-amazon.com/images/I/412vINaBcEL._AC_SX679_.jpg',
      scores: { Construcción: 95, Sensibilidad: 95, Ligereza: 92, 'Calidad/Precio': 65, 'Resistencia salada': 95 },
    },
    {
      asin: 'B098131M93',
      title: 'Daiwa Crosscast Surf 33 423H',
      price: '~108€',
      rating: 4.7,
      image: 'https://m.media-amazon.com/images/I/4120fFTOrzL._AC_SX679_.jpg',
      scores: { Construcción: 80, Sensibilidad: 78, Ligereza: 75, 'Calidad/Precio': 90, 'Resistencia salada': 80 },
    },
    {
      asin: 'B0FYFMKZXZ',
      title: 'PENN Squadron IV Carbono 24T',
      price: '86-110€',
      rating: 5.0,
      image: 'https://m.media-amazon.com/images/I/41sU7nzwDUL._AC_SX679_.jpg',
      scores: { Construcción: 82, Sensibilidad: 80, Ligereza: 78, 'Calidad/Precio': 82, 'Resistencia salada': 85 },
    },
    {
      asin: 'B0844Y3MNW',
      title: 'Daiwa Ninja Surf SCW 420',
      price: '~125€',
      rating: 4.3,
      image: 'https://m.media-amazon.com/images/I/41+EnSD8WGL._AC_SY879_.jpg',
      scores: { Construcción: 72, Sensibilidad: 68, Ligereza: 65, 'Calidad/Precio': 85, 'Resistencia salada': 75 },
    },
    {
      asin: 'B09TTPSLZN',
      title: 'Mitchell Adventure 2 Surf 3.9m',
      price: '24-55€',
      rating: 4.0,
      image: 'https://m.media-amazon.com/images/I/41V-tJAPmUL._AC_SX679_.jpg',
      scores: { Construcción: 60, Sensibilidad: 50, Ligereza: 55, 'Calidad/Precio': 95, 'Resistencia salada': 70 },
    },
  ])

  const fullContent = content + `\n\n<!-- PRODUCTS_DATA: ${productsData} -->`

  const existing = await db.execute({
    sql: 'SELECT id FROM posts WHERE slug = ?',
    args: [slug],
  })

  if (existing.rows.length > 0) {
    const id = existing.rows[0].id as string
    await db.execute({
      sql: `UPDATE posts SET title = ?, excerpt = ?, content = ?, featuredImage = ?,
        author = ?, category = ?, tags = ?, relatedAsins = ?, updatedAt = ?
        WHERE id = ?`,
      args: [
        'Las 5 mejores cañas de surfcasting calidad-precio en 2026',
        '¿Buscas una caña de surfcasting? Comparamos los mejores modelos de 2026: Shimano Ultegra XR Surf, Daiwa Crosscast Surf 33, PENN Squadron IV, Daiwa Ninja Surf SCW y Mitchell Adventure 2. Guía de compra con pros, contras y precios actualizados.',
        fullContent,
        'https://m.media-amazon.com/images/I/4120fFTOrzL._AC_SX679_.jpg',
        'PesCatch',
        'Cañas',
        JSON.stringify(['cañas surfcasting', 'surfcasting', 'cañas pesca', 'mejores cañas surfcasting', 'guias compra']),
        JSON.stringify(['B0F4XJ85B4', 'B098131M93', 'B0FYFMKZXZ', 'B0844Y3MNW', 'B09TTPSLZN']),
        now,
        id,
      ],
    })
    console.log(`✅ Blog post updated: ${slug}`)
  } else {
    await db.execute({
      sql: `INSERT INTO posts (id, title, slug, excerpt, content, featuredImage, author, category, tags, relatedAsins, hidden, publishedAt, createdAt, updatedAt)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        `post_${Date.now()}`,
        'Las 5 mejores cañas de surfcasting calidad-precio en 2026',
        slug,
        '¿Buscas una caña de surfcasting? Comparamos los mejores modelos de 2026: Shimano Ultegra XR Surf, Daiwa Crosscast Surf 33, PENN Squadron IV, Daiwa Ninja Surf SCW y Mitchell Adventure 2. Guía de compra con pros, contras y precios actualizados.',
        fullContent,
        'https://m.media-amazon.com/images/I/4120fFTOrzL._AC_SX679_.jpg',
        'PesCatch',
        'Cañas',
        JSON.stringify(['cañas surfcasting', 'surfcasting', 'cañas pesca', 'mejores cañas surfcasting', 'guias compra']),
        JSON.stringify(['B0F4XJ85B4', 'B098131M93', 'B0FYFMKZXZ', 'B0844Y3MNW', 'B09TTPSLZN']),
        0, now, now, now,
      ],
    })
    console.log(`✅ Blog post created: ${slug}`)
  }
}

seedBlogPost().catch(console.error)
