import { getDb, initSchema } from '../src/lib/db'

async function seedBlogPost() {
  const db = getDb()
  await initSchema()

  const slug = 'shimano-vs-daiwa-mejores-carretes-spinning'
  const now = new Date().toISOString()

  const content = [
    'Si estás buscando un carrete de spinning y no sabes si irte a Shimano o Daiwa, no eres el único. Son las dos marcas que dominan el mercado y cada una tiene sus fortalezas. En esta guía comparamos los mejores modelos de cada marca en distintos rangos de precio para que sepas exactamente cuál te conviene.',
    '',
    '## Para los que tienen prisa',
    '',
    '**Shimano Sienna** es el mejor carrete calidad-precio para empezar (40€). En gama media, el **Daiwa Ninja LT** (60€) supera al Shimano Catana en suavidad y ligereza. Y si quieres lo mejor sin irte a precios de locura, el **Shimano Sedona** (75€) es el más equilibrado de todos.',
    '',
    '---',
    '<!--PRODUCT_IMG:1-->',
    '',
    '## 1. Shimano Sienna 4000 — El rey de la entrada de gama',
    '',
    'El **Shimano Sienna** es, probablemente, el carrete más vendido de la historia del spinning. Y no es casualidad. Por unos 40€ tienes un carrete con 3+1 rodamientos, sistema de freno delantero fiable y una construcción que aguanta temporadas de uso intensivo.',
    '',
    'La versión actual incorpora la tecnología Propulsion Line Management de Shimano, que reduce los nudos de viento y mejora el lance. No es el más suave ni el más ligero, pero a este precio es imbatible.',
    '',
    'Lo usan desde principiantes que compran su primer equipo hasta pescadores veteranos que necesitan un carrete de repuesto fiable. El tamaño 4000 es el más polivalente: vale para spinning ligero de lubina, rockfishing e incluso algún lance a curricán.',
    '',
    '- **Peso:** 290g | **Rodamientos:** 3+1 | **Recuperación:** 82cm | **Freno:** 8.5kg',
    '- Ideal para principiantes y como segundo carrete',
    '- Perfecto para lubina, trucha, black bass y pesca en agua dulce',
    '- Lo mejor: Precio imbatible, fiabilidad Shimano, fácil mantenimiento',
    '',
    'Si tu presupuesto es ajustado, no lo dudes. Es el carrete que recomendamos a todo el que empieza.',
    '',
    '---',
    '<!--PRODUCT_IMG:2-->',
    '',
    '## 2. Daiwa Ninja LT 23 4000 — El mejor de la gama media',
    '',
    'El **Daiwa Ninja LT 23** es, para nosotros, el carrete más equilibrado del mercado. Por 60€ tienes tecnología LT (Light & Tough) de Daiwa: chasis de composite ultraligero, rotor Air Rotor que reduce el peso y la inercia, y 5+1 rodamientos que proporcionan una suavidad de giro excepcional.',
    '',
    'La diferencia con el Sienna se nota nada más cogerlo: pesa 60 gramos menos y la recuperación es mucho más sedosa. El sistema ATD (Automatic Tournament Drag) de Daiwa es famoso por su suavidad al ceder línea: importante cuando pescas con trenzado fino o tienes un pez grande al otro lado.',
    '',
    'Si pescas con regularidad y quieres notar un salto de calidad respecto a los carretes de entrada, este es tu carrete. Además, la estética y los acabados están a años luz del Sienna.',
    '',
    '- **Peso:** 230g | **Rodamientos:** 5+1 | **Recuperación:** 87cm | **Freno:** 12kg',
    '- Ideal para spinning medio y pescadores con cierta experiencia',
    '- Perfecto para lubina, bar, anjova y cualquier depredador de costa',
    '- Lo mejor: Ligereza, suavidad de giro, freno ATD progresivo',
    '',
    'La opción más recomendable para el pescador que pesca 2-3 veces al mes y quiere calidad sin hipotecarse.',
    '',
    '---',
    '<!--PRODUCT_IMG:3-->',
    '',
    '## 3. Shimano Catana 4000 — El clásico de gama media',
    '',
    'El **Shimano Catana** es la respuesta de Shimano a la gama media. Con 4+1 rodamientos, chasis XT-7 de grafito y un diseño que ha ido refinándose durante años, es un carrete sólido y fiable. La palanca de recogida es de una sola pieza, lo que da una sensación de robustez que otros carretes no tienen.',
    '',
    'Comparado con el Ninja LT, el Catana es ligeramente más pesado y menos suave, pero a cambio ofrece ese tacto Shimano que muchos pescadores prefieren: más directo, más "mecánico". El Varispeed Oscillation proporciona un devanado muy uniforme.',
    '',
    '- **Peso:** 280g | **Rodamientos:** 4+1 | **Recuperación:** 82cm | **Freno:** 8.5kg',
    '- Ideal para pescadores que prefieren el tacto Shimano',
    '- Perfecto para spinning en costa, agua dulce y depredadores medios',
    '- Lo mejor: Fiabilidad legendaria, devanado uniforme, recambios fáciles',
    '',
    'Un clásico que nunca falla. Si eres de los que prefieren Shimano por filosofía, el Catana es tu opción lógica.',
    '',
    '---',
    '<!--PRODUCT_IMG:4-->',
    '',
    '## 4. Daiwa Laguna LT 20 4000 — Calidad-precio imbatible',
    '',
    'El **Daiwa Laguna LT** es el hermano pequeño del Ninja, pero no te equivoques: comparte mucha tecnología. Mismo chasis LT ultraligero, mismo rotor Air Rotor, y 4+1 rodamientos que ofrecen una suavidad excelente para su rango de precio.',
    '',
    'La principal diferencia con el Ninja es el número de rodamientos (4+1 vs 5+1) y algunos acabados. Pero en el agua, la diferencia es mínima. Si el Ninja está fuera de presupuesto, el Laguna te dará el 90% de la experiencia por 15€ menos.',
    '',
    '- **Peso:** 245g | **Rodamientos:** 4+1 | **Recuperación:** 84cm | **Freno:** 10kg',
    '- Ideal para quien busca tecnología LT al mejor precio',
    '- Perfecto para spinning ligero, rockfishing y pesca variada',
    '- Lo mejor: Tecnología LT a precio reducido, ligero, suave',
    '',
    'La opción más inteligente de Daiwa en relación calidad-precio.',
    '',
    '---',
    '<!--PRODUCT_IMG:5-->',
    '',
    '## 5. Shimano Sedona 4000 — El más equilibrado',
    '',
    'El **Shimano Sedona** es el punto dulce de la gama Shimano. Por 75€ incorpora la tecnología Hagane (engranajes forjados en frío), que tradicionalmente estaba reservada para carretes mucho más caros. Esto se traduce en una mecánica más precisa, más duradera y mucho más suave.',
    '',
    'Con 3+1 rodamientos (Shimano usa menos rodamientos pero de mayor calidad) y el sistema G-Free Body (centro de gravedad desplazado hacia la caña), el Sedona es el carrete más cómodo de usar de toda la comparativa. Fatiga menos en jornadas largas.',
    '',
    '- **Peso:** 265g | **Rodamientos:** 3+1 | **Recuperación:** 91cm | **Freno:** 9kg',
    '- Ideal para pescadores frecuentes que quieren calidad duradera',
    '- Perfecto para todo tipo de spinning en costa y embarcación',
    '- Lo mejor: Engranajes Hagane, ergonomía G-Free, suavidad Shimano',
    '',
    'Nuestra recomendación personal para el que pesca cada fin de semana. Los engranajes Hagane marcan la diferencia.',
    '',
    '---',
    '<!--PRODUCT_IMG:6-->',
    '',
    '## 6. Daiwa Exceler 4000 — El tapado de la gama alta',
    '',
    'Cerramos con el **Daiwa Exceler**, un carrete que compite en el segmento de los 75-80€ y que muchos pescadores pasan por alto. Monta 5+1 rodamientos, chasis de composite de alta rigidez, rotor Air Bail y el sistema de freno ATD que ya conocemos del Ninja.',
    '',
    'Donde el Exceler marca la diferencia es en la rigidez del chasis: al clavar un pez grande, no notas esa flexión del cuerpo que sí aparece en carretes más baratos. La recuperación es rapidísima y el devanado, gracias al sistema Twist Buster II, es impecable incluso con trenzados finos.',
    '',
    '- **Peso:** 255g | **Rodamientos:** 5+1 | **Recuperación:** 99cm | **Freno:** 12kg',
    '- Ideal para pescadores exigentes que no quieren pagar un Stradic o un Certate',
    '- Perfecto para spinning pesado, jigging ligero y depredadores grandes',
    '- Lo mejor: Rigidez del chasis, recuperación ultrarrápida, freno potente',
    '',
    'Si puedes estirar el presupuesto a 75€, el Exceler es el carrete más completo de esta comparativa.',
    '',
    '---',
    '',
    '## Shimano vs Daiwa — La decisión final',
    '',
    'Después de analizar los 6 carretes, nuestra recomendación depende de tu presupuesto y frecuencia de pesca:',
    '',
    '- **Menos de 35€**: Shimano Sienna. Simplemente no hay nada mejor a este precio.',
    '- **45-50€**: Empate técnico. Daiwa Laguna LT por suavidad y peso, Shimano Catana por tacto y fiabilidad.',
    '- **60-65€**: Daiwa Ninja LT. El más equilibrado de toda la comparativa.',
    '- **68-75€**: Shimano Sedona si valoras la durabilidad, Daiwa Exceler si prefieres velocidad de recogida.',
    '',
    'Y una reflexión final: no te obsesiones con la marca. Tanto Shimano como Daiwa fabrican productos excelentes. La diferencia real está en el modelo concreto y en cómo se adapta a tu estilo de pesca. Prueba, compara y quédate con el que mejor se sienta en tu mano.',
    '',
    '**Los Shimano tienen un tacto más mecánico y directo. Los Daiwa son más sedosos y ligeros.** Con el tiempo desarrollarás preferencia por uno u otro. Pero ninguno de los carretes de esta lista te va a defraudar.',
    '',
    '---',
    '',
    '## FAQ',
    '',
    '### ¿Shimano o Daiwa para empezar en el spinning?',
    'Shimano Sienna, sin duda. Por 31€ tienes un carrete fiable con recambios y servicio técnico en toda España. Cuando lleves un año pescando y sepas qué tipo de spinning te gusta, saltas al Ninja LT o al Sedona.',
    '',
    '### ¿Qué significa LT en los carretes Daiwa?',
    'LT significa Light & Tough. Es una filosofía de diseño de Daiwa que busca reducir el peso del carrete usando materiales compuestos avanzados sin sacrificar resistencia. Los carretes LT suelen ser más ligeros que sus equivalentes tradicionales.',
    '',
    '### ¿Los carretes Shimano aguantan el agua salada?',
    'Sí, pero requieren mantenimiento. Acláralos con agua dulce después de cada jornada de pesca en mar y engrasa los rodamientos cada 6 meses. Los modelos con protección X-Ship (Sedona hacia arriba) aguantan mejor la sal.',
    '',
    '### ¿Merece la pena comprar un carrete caro si solo pesco en vacaciones?',
    'No. Con un Sienna o un Laguna LT vas sobrado. La diferencia de precio (30€ vs 100€+) solo se nota cuando pescas muy a menudo y empiezas a apreciar matices como la suavidad del freno o la rigidez del chasis al clavar.',
    '',
    '### ¿Qué tamaño de carrete necesito?',
    'El 4000 es el más polivalente para spinning en costa. El 2500-3000 para agua dulce y spinning ultraligero. El 5000-6000 para surfcasting o spinning pesado a grandes depredadores.',
  ].join('\n')

  const productsData = JSON.stringify([
    {
      asin: 'B07WGXWBGB',
      title: 'Shimano Sienna 4000 FG',
      price: '40€',
      rating: 4.5,
      image: 'https://m.media-amazon.com/images/I/71hdFtzFJ6L._AC_SX679_.jpg',
      scores: { Suavidad: 65, Ligereza: 60, 'Potencia freno': 70, 'Calidad/Precio': 95, Durabilidad: 75 },
    },
    {
      asin: 'B0CH17B8Z1',
      title: 'Daiwa Ninja LT 23 4000-C',
      price: '60€',
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/71qfny63ZvL._AC_SX679_.jpg',
      scores: { Suavidad: 88, Ligereza: 92, 'Potencia freno': 90, 'Calidad/Precio': 88, Durabilidad: 82 },
    },
    {
      asin: 'B0B2X3V297',
      title: 'Shimano Catana FE 4000 HG',
      price: '45€',
      rating: 4.4,
      image: 'https://m.media-amazon.com/images/I/81-c7Q6Iq6L._AC_SX679_.jpg',
      scores: { Suavidad: 72, Ligereza: 65, 'Potencia freno': 68, 'Calidad/Precio': 82, Durabilidad: 88 },
    },
    {
      asin: 'B088LXGL5C',
      title: 'Daiwa Laguna LT 4000',
      price: '43€',
      rating: 4.5,
      image: 'https://m.media-amazon.com/images/I/61n2t+0XwnL._AC_SX679_.jpg',
      scores: { Suavidad: 82, Ligereza: 88, 'Potencia freno': 85, 'Calidad/Precio': 92, Durabilidad: 78 },
    },
    {
      asin: 'B0CBQLYLBS',
      title: 'Shimano Sedona FJ 4000',
      price: '75€',
      rating: 4.6,
      image: 'https://m.media-amazon.com/images/I/51ZagATcGxL._AC_SX679_.jpg',
      scores: { Suavidad: 90, Ligereza: 80, 'Potencia freno': 82, 'Calidad/Precio': 82, Durabilidad: 92 },
    },
    {
      asin: 'B08PKF33KV',
      title: 'Daiwa Exceler LT 4000-CP',
      price: '86€',
      rating: 4.5,
      image: 'https://m.media-amazon.com/images/I/71-vGpnljPL._AC_SX679_.jpg',
      scores: { Suavidad: 85, Ligereza: 82, 'Potencia freno': 92, 'Calidad/Precio': 78, Durabilidad: 85 },
    },
  ])

  const fullContent = content + `\n\n<!-- PRODUCTS_DATA: ${productsData} -->`

  const id = `post_shimano_vs_daiwa_${Date.now()}`

  await db.execute({
    sql: `INSERT OR REPLACE INTO posts (id, title, slug, excerpt, content, featuredImage, author, category, tags, relatedAsins, publishedAt, createdAt, updatedAt)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      id,
      'Shimano vs Daiwa 2026: los mejores carretes de spinning comparados',
      slug,
      '¿Shimano o Daiwa? Comparamos los 6 mejores carretes de spinning calidad-precio de 2026: Sienna, Ninja LT, Catana, Laguna, Sedona y Exceler. Tabla comparativa, puntuaciones y guía de compra.',
      fullContent,
      '',
      'PesCatch',
      'Carretes',
      JSON.stringify(['shimano', 'daiwa', 'carretes spinning', 'comparativa', 'guias compra']),
      JSON.stringify(['B07WGXWBGB', 'B0CH17B8Z1', 'B0B2X3V297', 'B088LXGL5C', 'B0CBQLYLBS', 'B08PKF33KV']),
      now,
      now,
      now,
    ],
  })

  console.log(`✅ Blog post seeded: ${slug}`)
}

seedBlogPost().catch(console.error)
